local _,Analyzer=...if not Analyzer then return end
local module={}
local utils=Analyzer.utils
module.name="Death Knight - Unholy"
module.class="DEATHKNIGHT"
module.specKey="unholy"
module.specIndex=3
module.specId=252
local SPELL_FESTERING_STRIKE=85948
local SPELL_SCOURGE_STRIKE=55090
local SPELL_DEATH_COIL=47541
local SPELL_DARK_TRANSFORMATION=63560
local SPELL_OUTBREAK=77575
local SPELL_PLAGUE_STRIKE=45462
local SPELL_BLOOD_PLAGUE=55078
local SPELL_FROST_FEVER=55095
local SPELL_UNHOLY_FRENZY=49016
local SPELL_SOUL_REAPER=130736
local SPELL_SUMMON_GARGOYLE=49206
local SPELL_SUDDEN_DOOM=81340
local SPELL_DEATH_AND_DECAY=43265
local COOLDOWN_DARK_TRANSFORMATION=60
local COOLDOWN_UNHOLY_FRENZY=180
local COOLDOWN_GARGOYLE=180
local SOUND_KEY_SUDDEN_DOOM="suddenDoom"
local SOUND_KEY_DARK_TRANSFORMATION="darkTransformation"
local SOUND_KEY_SOUL_REAPER="soulReaper"
local TRACKED_BUFFS={[SPELL_DARK_TRANSFORMATION]=true,[SPELL_UNHOLY_FRENZY]=true,[SPELL_SUDDEN_DOOM]=true}
local TRACKED_DEBUFFS={[SPELL_BLOOD_PLAGUE]=true,[SPELL_FROST_FEVER]=true}
local TRACKED_CASTS={[SPELL_FESTERING_STRIKE]=true,[SPELL_SCOURGE_STRIKE]=true,[SPELL_DEATH_COIL]=true,[SPELL_DARK_TRANSFORMATION]=true,[SPELL_OUTBREAK]=true,[SPELL_PLAGUE_STRIKE]=true,[SPELL_UNHOLY_FRENZY]=true,[SPELL_SOUL_REAPER]=true,[SPELL_SUMMON_GARGOYLE]=true,[SPELL_DEATH_AND_DECAY]=true}
local function EH(c,s)c[s]=c[s]or{}return c[s]end
function module.SupportsSpec(a)if a.player.class~=module.class then return false end if a.player.specId==module.specId then return true end local sk=utils.NormalizeSpecKey(a.player.specName)if sk==module.specKey then return true end if a.player.specIndex==module.specIndex then return true end return false end
function module.OnPlayerInit(a)if a.player.class~=module.class then return end if a.player.specName~="Unknown"then return end if IsSpellKnown and IsSpellKnown(SPELL_SCOURGE_STRIKE)and IsSpellKnown(SPELL_FESTERING_STRIKE)then a.player.specName="Unholy"a.player.specId=a.player.specId or module.specId a.player.specIndex=a.player.specIndex or module.specIndex end end
function module.GetDefaultSettings()return{sounds={[SOUND_KEY_SUDDEN_DOOM]={enabled=true,sound="Sound\\Interface\\RaidWarning.ogg"},[SOUND_KEY_DARK_TRANSFORMATION]={enabled=true,sound="Sound\\Interface\\MapPing.ogg"},[SOUND_KEY_SOUL_REAPER]={enabled=true,sound="Sound\\Interface\\RaidWarning.ogg"}}}end
function module.GetSoundOptions()return{{key=SOUND_KEY_SUDDEN_DOOM,label="Sudden Doom Proc"},{key=SOUND_KEY_DARK_TRANSFORMATION,label="Dark Transformation Ready"},{key=SOUND_KEY_SOUL_REAPER,label="Soul Reaper (Target <35%)"}}end
function module.IsTrackedBuffSpell(s)return TRACKED_BUFFS[s]==true end
function module.IsTrackedDebuffSpell(s)return TRACKED_DEBUFFS[s]==true end
function module.IsTrackedCast(s)return TRACKED_CASTS[s]==true end
function module.ShouldRecordCast(e)if not e or not e.spellId then return false end return TRACKED_CASTS[e.spellId]==true end
function module.GetProcInfo(s)if s==SPELL_SUDDEN_DOOM then return{soundKey=SOUND_KEY_SUDDEN_DOOM,priority=3}end return nil end
function module.InitFight(_,f)f.procs={suddenDoomProcs=0,suddenDoomConsumed=0}f.counts={scourgeStrikeCasts=0,deathCoilCasts=0,soulReaperCasts=0}f.cooldowns={darkTransformationLast=0,gargoyleLast=0,unholyFrenzyLast=0}f.castLog={}f.buffHistory={}f.debuffHistory={}f.rotation={totalCasts=0,optimalCasts=0,suboptimalCasts=0,mistakes={},penaltySum=0}end
function module.TrackSpellCast(a,s,t)local f=a.fight if not f or not TRACKED_CASTS[s]then return end local n=utils.NormalizeTimestamp(t)f.spells[s]=(f.spells[s]or 0)+1 table.insert(f.castLog,{spellId=s,timestamp=n})if s==SPELL_SCOURGE_STRIKE then f.counts.scourgeStrikeCasts=f.counts.scourgeStrikeCasts+1 elseif s==SPELL_DEATH_COIL then f.counts.deathCoilCasts=f.counts.deathCoilCasts+1 local b=f.buffs[SPELL_SUDDEN_DOOM]if b then f.procs.suddenDoomConsumed=f.procs.suddenDoomConsumed+1 f.buffs[SPELL_SUDDEN_DOOM]=nil end elseif s==SPELL_SOUL_REAPER then f.counts.soulReaperCasts=f.counts.soulReaperCasts+1 a:AddEventLog(n,"Soul Reaper",s)elseif s==SPELL_DARK_TRANSFORMATION then f.cooldowns.darkTransformationLast=n a:AddTimelineEvent(s,n,"cooldown")a:AddEventLog(n,"Dark Transformation",s)elseif s==SPELL_SUMMON_GARGOYLE then f.cooldowns.gargoyleLast=n a:AddTimelineEvent(s,n,"cooldown")a:AddEventLog(n,"Summon Gargoyle",s)elseif s==SPELL_UNHOLY_FRENZY then f.cooldowns.unholyFrenzyLast=n a:AddTimelineEvent(s,n,"cooldown")a:AddEventLog(n,"Unholy Frenzy",s)end local cS={[SPELL_FESTERING_STRIKE]=true,[SPELL_SCOURGE_STRIKE]=true,[SPELL_DEATH_COIL]=true,[SPELL_SOUL_REAPER]=true}if cS[s]and f.rotation then local ev=module.EvaluateCast(a,f,s,n)if ev then module.RecordCastEvaluation(f,ev,n)end end end
function module.TrackAura(a,se,s,am,t)local f=a.fight if not f then return end local n=utils.NormalizeTimestamp(t)if se=="SPELL_AURA_APPLIED"or se=="SPELL_AURA_APPLIED_DOSE"or se=="SPELL_AURA_REFRESH"then local st=am or 1 local b=f.buffs[s]local isR=(se=="SPELL_AURA_REFRESH")if b and isR and b.since then f.buffUptime[s]=(f.buffUptime[s]or 0)+(n-b.since)end if not b then b={stacks=st,since=n}f.buffs[s]=b else b.stacks=st b.since=b.since or n end if isR then b.since=n end local h=EH(f.buffHistory,s)if isR and b.historyEntry and not b.historyEntry.removed then b.historyEntry.removed=n end if not b.historyEntry or isR then b.historyEntry={applied=n}table.insert(h,b.historyEntry)end if s==SPELL_SUDDEN_DOOM then if not isR then f.procs.suddenDoomProcs=f.procs.suddenDoomProcs+1 a:AddTimelineEvent(s,n,"proc")end a:PlayAlertSound(SOUND_KEY_SUDDEN_DOOM,n)end elseif se=="SPELL_AURA_REMOVED"then local b=f.buffs[s]if b then if b.since then f.buffUptime[s]=(f.buffUptime[s]or 0)+(n-b.since)end if b.historyEntry and not b.historyEntry.removed then b.historyEntry.removed=n end end f.buffs[s]=nil end end
function module.TrackDebuff(a,se,s,dG,dN,t)local f=a.fight if not f or not TRACKED_DEBUFFS[s]then return end local n=utils.NormalizeTimestamp(t)if not f.primaryTargetGUID then f.primaryTargetGUID=dG end if dG and f.primaryTargetGUID and dG~=f.primaryTargetGUID then return end if dG then f.targets[dG]=true end local d=f.debuffs[s]local h=EH(f.debuffHistory,s)if se=="SPELL_AURA_APPLIED"then f.debuffs[s]={since=n,targetGUID=dG}local e={applied=n}table.insert(h,e)f.debuffs[s].historyEntry=e elseif se=="SPELL_AURA_REFRESH"then if d and d.since then f.debuffUptime[s]=(f.debuffUptime[s]or 0)+(n-d.since)end if d and d.historyEntry and not d.historyEntry.removed then d.historyEntry.removed=n end f.debuffs[s]={since=n,targetGUID=dG}local e={applied=n}table.insert(h,e)f.debuffs[s].historyEntry=e elseif se=="SPELL_AURA_REMOVED"then if d and d.since then f.debuffUptime[s]=(f.debuffUptime[s]or 0)+(n-d.since)end if d and d.historyEntry and not d.historyEntry.removed then d.historyEntry.removed=n end f.debuffs[s]=nil end end
function module.Analyze(a,f,c)local m={}local i={}local sc=100 if c.duration<15 then utils.AddIssue(i,"Walka zbyt krotka.")return{score=0,metrics=m,issues=i}end local function AM(l,s,v,p,st,it,pen)table.insert(m,{label=l,spellId=s,valueText=v or"",percent=p,status=st or"info"})utils.AddIssue(i,it)if pen and pen>0 then sc=utils.Clamp(sc-pen,0,100)end end local bpUp=utils.SafePercent(f.debuffUptime[SPELL_BLOOD_PLAGUE]or 0,c.duration)local bpSt=utils.StatusForPercent(bpUp,0.90,0.75)AM("Blood Plague uptime",SPELL_BLOOD_PLAGUE,utils.FormatPercent(bpUp),bpUp,bpSt,bpSt=="bad"and"Niski uptime Blood Plague."or(bpSt=="warn"and"BP moglby byc wyzszy."or nil),bpSt=="bad"and 10 or(bpSt=="warn"and 5 or 0))local ffUp=utils.SafePercent(f.debuffUptime[SPELL_FROST_FEVER]or 0,c.duration)local ffSt=utils.StatusForPercent(ffUp,0.90,0.75)AM("Frost Fever uptime",SPELL_FROST_FEVER,utils.FormatPercent(ffUp),ffUp,ffSt,ffSt=="bad"and"Niski uptime Frost Fever."or(ffSt=="warn"and"FF moglby byc wyzszy."or nil),ffSt=="bad"and 10 or(ffSt=="warn"and 5 or 0))local dt=f.spells[SPELL_DARK_TRANSFORMATION]or 0 local expDT=utils.ExpectedUses(c.duration,COOLDOWN_DARK_TRANSFORMATION,10)if expDT>0 then local dtP=utils.SafePercent(dt,expDT)local dtSt=utils.StatusForPercent(dtP,0.80,0.60)AM("Dark Transformation uzycia",SPELL_DARK_TRANSFORMATION,string.format("%d/%d",dt,expDT),math.min(dtP or 0,1),dtSt,dtSt=="bad"and"Za malo Dark Transformation."or(dtSt=="warn"and"DT uzywany zbyt rzadko."or nil),dtSt=="bad"and 10 or(dtSt=="warn"and 5 or 0))end local sdP=f.procs.suddenDoomProcs or 0 local sdC=f.procs.suddenDoomConsumed or 0 if sdP>0 then local sdU=utils.SafePercent(sdC,sdP)local sdSt=utils.StatusForPercent(sdU,0.85,0.70)AM("Sudden Doom wykorzystanie",SPELL_SUDDEN_DOOM,string.format("%s (%d/%d)",utils.FormatPercent(sdU),sdC,sdP),sdU,sdSt,sdSt=="bad"and"Za duzo SD nie zuzyte."or(sdSt=="warn"and"Czesc SD sie marnuje."or nil),sdSt=="bad"and 10 or(sdSt=="warn"and 5 or 0))end if f.rotation and f.rotation.totalCasts>0 then local rS=module.GetRotationScore(f)if rS then local rA=rS.accuracy or 0 local rSt=utils.StatusForPercent(rA,0.85,0.70)AM("Dokladnosc rotacji (APL)",nil,string.format("%.0f%% (%d/%d)",rA*100,rS.optimalCasts,rS.totalCasts),rA,rSt,rSt=="bad"and"Niska dokladnosc."or(rSt=="warn"and"Srednia dokladnosc."or nil),rSt=="bad"and 10 or(rSt=="warn"and 5 or 0))if rS.mistakes and #rS.mistakes>0 then local mC={}for _,mk in ipairs(rS.mistakes)do mC[mk.reason or"Unknown"]=(mC[mk.reason or"Unknown"]or 0)+1 end local sM={}for r,ct in pairs(mC)do table.insert(sM,{reason=r,count=ct})end table.sort(sM,function(x,y)return x.count>y.count end)for j=1,math.min(3,#sM)do local mk=sM[j]if mk.count>=2 then utils.AddIssue(i,string.format("Blad rotacji (%dx): %s",mk.count,mk.reason))end end end end end sc=utils.Clamp(sc,0,100)return{score=sc,metrics=m,issues=i}end
function module.GetLiveScore(a,f)if not f then return nil end local n=GetTime()local d=n-f.startTime if d<5 then return nil end return 100 end
local function CPB(s)if not s then return false end for i=1,40 do local _,_,_,_,_,_,_,_,_,aS=UnitBuff("player",i)if not aS then break end if aS==s then return true end end return false end
local function CTD(s)if not s or not UnitExists("target")then return false,0 end for i=1,40 do local _,_,_,_,_,eT,_,c,_,_,aS=UnitDebuff("target",i)if not aS then break end if aS==s and c=="player"then local r=eT and(eT-GetTime())or 0 return true,r end end return false,0 end
local function TargetLowHP()if not UnitExists("target")then return false end local hp=UnitHealth("target")local maxHP=UnitHealthMax("target")if maxHP==0 then return false end return(hp/maxHP)<0.35 end
local function GRP()return UnitPower("player",6)or 0 end
function module.GetLiveAdvice(a,f)if not f then return""end local n=GetTime()local d=n-f.startTime local rp=GRP()local hasSD=CPB(SPELL_SUDDEN_DOOM)if TargetLowHP()and utils.IsSpellReady(SPELL_SOUL_REAPER)then return"Soul Reaper! (Target <35%)"end if hasSD then return"Death Coil! (Sudden Doom)"end if utils.IsSpellReady(SPELL_DARK_TRANSFORMATION)then return"Dark Transformation!"end if UnitExists("target")then local hasBP,bpR=CTD(SPELL_BLOOD_PLAGUE)local hasFF,ffR=CTD(SPELL_FROST_FEVER)if(not hasBP or not hasFF)and d>2 then return"Outbreak! (brak chorob)"end if(hasBP and bpR>0 and bpR<4)or(hasFF and ffR>0 and ffR<4)then return"Odswiez choroby!"end end if rp>=90 then return"Death Coil! (wysoki RP)"end return""end
function module.GetAdviceSpellIcon(a,f)if not f then return nil end local n=GetTime()local d=n-f.startTime local rp=GRP()local hasSD=CPB(SPELL_SUDDEN_DOOM)if TargetLowHP()and utils.IsSpellReady(SPELL_SOUL_REAPER)then return SPELL_SOUL_REAPER end if hasSD then return SPELL_DEATH_COIL end if utils.IsSpellReady(SPELL_DARK_TRANSFORMATION)then return SPELL_DARK_TRANSFORMATION end if UnitExists("target")then local hasBP,bpR=CTD(SPELL_BLOOD_PLAGUE)local hasFF,ffR=CTD(SPELL_FROST_FEVER)if(not hasBP or not hasFF)and d>2 then return SPELL_OUTBREAK end if(hasBP and bpR>0 and bpR<4)or(hasFF and ffR>0 and ffR<4)then return SPELL_OUTBREAK end end if rp>=90 then return SPELL_DEATH_COIL end return nil end
local APL_PRIORITY={{id="sr",spellId=SPELL_SOUL_REAPER,name="Soul Reaper",condition=function(s)return s.targetLow and s.srReady end,priority=1,category="execute"},{id="dc_sd",spellId=SPELL_DEATH_COIL,name="DC(SD)",condition=function(s)return s.suddenDoom end,priority=2,category="proc"},{id="dt",spellId=SPELL_DARK_TRANSFORMATION,name="Dark Transformation",condition=function(s)return s.dtReady end,priority=3,category="cooldown"},{id="ob",spellId=SPELL_OUTBREAK,name="Outbreak",condition=function(s)return(s.bpMissing or s.ffMissing)and s.duration>2 end,priority=4,category="dot"},{id="ss",spellId=SPELL_SCOURGE_STRIKE,name="Scourge Strike",condition=function(s)return true end,priority=5,category="core"},{id="fs",spellId=SPELL_FESTERING_STRIKE,name="Festering Strike",condition=function(s)return true end,priority=6,category="core"},{id="dc",spellId=SPELL_DEATH_COIL,name="Death Coil",condition=function(s)return s.rp>=90 end,priority=7,category="dump"}}
local function GCS(a,f)local s={duration=0,targetLow=false,srReady=false,suddenDoom=false,dtReady=false,bpMissing=false,ffMissing=false,rp=0}if not f then return s end local n=GetTime()s.duration=n-(f.startTime or n)s.targetLow=TargetLowHP()s.srReady=utils.IsSpellReady(SPELL_SOUL_REAPER)s.suddenDoom=CPB(SPELL_SUDDEN_DOOM)s.dtReady=utils.IsSpellReady(SPELL_DARK_TRANSFORMATION)s.rp=GRP()if UnitExists("target")and s.duration>2 then local hasBP,_=CTD(SPELL_BLOOD_PLAGUE)local hasFF,_=CTD(SPELL_FROST_FEVER)s.bpMissing=not hasBP s.ffMissing=not hasFF end return s end
function module.GetNextAPLAction(a,f)local s=GCS(a,f)for _,act in ipairs(APL_PRIORITY)do if act.condition(s)then return act end end return APL_PRIORITY[#APL_PRIORITY]end
function module.GetAPLPriorityList()return APL_PRIORITY end
function module.GetRotationState(a,f)return GCS(a,f)end
function module.EvaluateCast(a,f,sid,ts)local nA=module.GetNextAPLAction(a,f)if not nA then return nil end local isO=(nA.spellId==sid)local pen=0 local rsn=""if not isO then local cP=nil for _,act in ipairs(APL_PRIORITY)do if act.spellId==sid then cP=act.priority break end end if cP then pen=math.abs(nA.priority-cP)*2 rsn=string.format("Powinienes: %s",nA.name)else pen=5 rsn="Spell poza APL"end end return{isOptimal=isO,penalty=pen,reason=rsn,expectedSpell=nA.spellId,expectedName=nA.name,actualSpell=sid}end
function module.RecordCastEvaluation(f,ev,ts)if not f.rotation then return end f.rotation.totalCasts=f.rotation.totalCasts+1 if ev.isOptimal then f.rotation.optimalCasts=f.rotation.optimalCasts+1 else f.rotation.suboptimalCasts=f.rotation.suboptimalCasts+1 f.rotation.penaltySum=f.rotation.penaltySum+ev.penalty table.insert(f.rotation.mistakes,{timestamp=ts,reason=ev.reason,penalty=ev.penalty,expected=ev.expectedName})end end
function module.GetRotationScore(f)if not f.rotation or f.rotation.totalCasts==0 then return nil end return{accuracy=f.rotation.optimalCasts/f.rotation.totalCasts,totalCasts=f.rotation.totalCasts,optimalCasts=f.rotation.optimalCasts,suboptimalCasts=f.rotation.suboptimalCasts,mistakes=f.rotation.mistakes,penaltySum=f.rotation.penaltySum}end
Analyzer:RegisterClassModule(module.class,module)
