local _,Analyzer=...if not Analyzer then return end
local module={}
local utils=Analyzer.utils
module.name="Druid - Feral"
module.class="DRUID"
module.specKey="feral"
module.specIndex=2
module.specId=103
local SPELL_RAKE=1822
local SPELL_RIP=1079
local SPELL_SHRED=5221
local SPELL_MANGLE=33876
local SPELL_FEROCIOUS_BITE=22568
local SPELL_SAVAGE_ROAR=52610
local SPELL_TIGERS_FURY=5217
local SPELL_BERSERK=106951
local SPELL_THRASH=106830
local SPELL_SWIPE=106785
local SPELL_OMEN_OF_CLARITY=16864
local SPELL_PREDATORY_SWIFTNESS=69369
local COOLDOWN_TIGERS_FURY=30
local COOLDOWN_BERSERK=180
local SOUND_KEY_OMEN_OF_CLARITY="omenOfClarity"
local SOUND_KEY_TIGERS_FURY="tigersFury"
local SOUND_KEY_PREDATORY_SWIFTNESS="predatorySwiftness"
local TRACKED_BUFFS={[SPELL_SAVAGE_ROAR]=true,[SPELL_TIGERS_FURY]=true,[SPELL_BERSERK]=true,[SPELL_OMEN_OF_CLARITY]=true,[SPELL_PREDATORY_SWIFTNESS]=true}
local TRACKED_DEBUFFS={[SPELL_RAKE]=true,[SPELL_RIP]=true,[SPELL_THRASH]=true}
local TRACKED_CASTS={[SPELL_RAKE]=true,[SPELL_RIP]=true,[SPELL_SHRED]=true,[SPELL_MANGLE]=true,[SPELL_FEROCIOUS_BITE]=true,[SPELL_SAVAGE_ROAR]=true,[SPELL_TIGERS_FURY]=true,[SPELL_BERSERK]=true,[SPELL_THRASH]=true,[SPELL_SWIPE]=true}
local function EH(c,s)c[s]=c[s]or{}return c[s]end
function module.SupportsSpec(a)if a.player.class~=module.class then return false end if a.player.specId==module.specId then return true end local sk=utils.NormalizeSpecKey(a.player.specName)if sk==module.specKey then return true end if a.player.specIndex==module.specIndex then return true end return false end
function module.OnPlayerInit(a)if a.player.class~=module.class then return end if a.player.specName~="Unknown"then return end if IsSpellKnown and IsSpellKnown(SPELL_SHRED)and IsSpellKnown(SPELL_RIP)and IsSpellKnown(SPELL_TIGERS_FURY)then a.player.specName="Feral"a.player.specId=a.player.specId or module.specId a.player.specIndex=a.player.specIndex or module.specIndex end end
function module.GetDefaultSettings()return{sounds={[SOUND_KEY_OMEN_OF_CLARITY]={enabled=true,sound="Sound\\Interface\\RaidWarning.ogg"},[SOUND_KEY_TIGERS_FURY]={enabled=true,sound="Sound\\Interface\\MapPing.ogg"},[SOUND_KEY_PREDATORY_SWIFTNESS]={enabled=true,sound="Sound\\Interface\\MapPing.ogg"}}}end
function module.GetSoundOptions()return{{key=SOUND_KEY_OMEN_OF_CLARITY,label="Omen of Clarity Proc"},{key=SOUND_KEY_TIGERS_FURY,label="Tiger's Fury Ready"},{key=SOUND_KEY_PREDATORY_SWIFTNESS,label="Predatory Swiftness"}}end
function module.IsTrackedBuffSpell(s)return TRACKED_BUFFS[s]==true end
function module.IsTrackedDebuffSpell(s)return TRACKED_DEBUFFS[s]==true end
function module.IsTrackedCast(s)return TRACKED_CASTS[s]==true end
function module.ShouldRecordCast(e)if not e or not e.spellId then return false end return TRACKED_CASTS[e.spellId]==true end
function module.GetProcInfo(s)if s==SPELL_OMEN_OF_CLARITY then return{soundKey=SOUND_KEY_OMEN_OF_CLARITY,priority=2}elseif s==SPELL_PREDATORY_SWIFTNESS then return{soundKey=SOUND_KEY_PREDATORY_SWIFTNESS,priority=2}end return nil end
function module.InitFight(_,f)f.procs={omenProcs=0,omenConsumed=0}f.counts={shredCasts=0,ferociousBiteCasts=0,ripCasts=0}f.cooldowns={tigersFuryLast=0,berserkLast=0}f.castLog={}f.buffHistory={}f.debuffHistory={}f.rotation={totalCasts=0,optimalCasts=0,suboptimalCasts=0,mistakes={},penaltySum=0}end
function module.TrackSpellCast(a,s,t)local f=a.fight if not f or not TRACKED_CASTS[s]then return end local n=utils.NormalizeTimestamp(t)f.spells[s]=(f.spells[s]or 0)+1 table.insert(f.castLog,{spellId=s,timestamp=n})if s==SPELL_SHRED then f.counts.shredCasts=f.counts.shredCasts+1 local b=f.buffs[SPELL_OMEN_OF_CLARITY]if b then f.procs.omenConsumed=f.procs.omenConsumed+1 f.buffs[SPELL_OMEN_OF_CLARITY]=nil end elseif s==SPELL_FEROCIOUS_BITE then f.counts.ferociousBiteCasts=f.counts.ferociousBiteCasts+1 elseif s==SPELL_RIP then f.counts.ripCasts=f.counts.ripCasts+1 elseif s==SPELL_TIGERS_FURY then f.cooldowns.tigersFuryLast=n a:AddTimelineEvent(s,n,"cooldown")a:AddEventLog(n,"Tiger's Fury",s)elseif s==SPELL_BERSERK then f.cooldowns.berserkLast=n a:AddTimelineEvent(s,n,"cooldown")a:AddEventLog(n,"Berserk",s)end local cS={[SPELL_SHRED]=true,[SPELL_RAKE]=true,[SPELL_RIP]=true,[SPELL_FEROCIOUS_BITE]=true,[SPELL_SAVAGE_ROAR]=true}if cS[s]and f.rotation then local ev=module.EvaluateCast(a,f,s,n)if ev then module.RecordCastEvaluation(f,ev,n)end end end
function module.TrackAura(a,se,s,am,t)local f=a.fight if not f then return end local n=utils.NormalizeTimestamp(t)if se=="SPELL_AURA_APPLIED"or se=="SPELL_AURA_APPLIED_DOSE"or se=="SPELL_AURA_REFRESH"then local st=am or 1 local b=f.buffs[s]local isR=(se=="SPELL_AURA_REFRESH")if b and isR and b.since then f.buffUptime[s]=(f.buffUptime[s]or 0)+(n-b.since)end if not b then b={stacks=st,since=n}f.buffs[s]=b else b.stacks=st b.since=b.since or n end if isR then b.since=n end local h=EH(f.buffHistory,s)if isR and b.historyEntry and not b.historyEntry.removed then b.historyEntry.removed=n end if not b.historyEntry or isR then b.historyEntry={applied=n}table.insert(h,b.historyEntry)end if s==SPELL_OMEN_OF_CLARITY then if not isR then f.procs.omenProcs=f.procs.omenProcs+1 end a:PlayAlertSound(SOUND_KEY_OMEN_OF_CLARITY,n)elseif s==SPELL_PREDATORY_SWIFTNESS then a:PlayAlertSound(SOUND_KEY_PREDATORY_SWIFTNESS,n)end elseif se=="SPELL_AURA_REMOVED"then local b=f.buffs[s]if b then if b.since then f.buffUptime[s]=(f.buffUptime[s]or 0)+(n-b.since)end if b.historyEntry and not b.historyEntry.removed then b.historyEntry.removed=n end end f.buffs[s]=nil end end
function module.TrackDebuff(a,se,s,dG,dN,t)local f=a.fight if not f or not TRACKED_DEBUFFS[s]then return end local n=utils.NormalizeTimestamp(t)if not f.primaryTargetGUID then f.primaryTargetGUID=dG end if dG and f.primaryTargetGUID and dG~=f.primaryTargetGUID then return end if dG then f.targets[dG]=true end local d=f.debuffs[s]local h=EH(f.debuffHistory,s)if se=="SPELL_AURA_APPLIED"then f.debuffs[s]={since=n,targetGUID=dG}local e={applied=n}table.insert(h,e)f.debuffs[s].historyEntry=e elseif se=="SPELL_AURA_REFRESH"then if d and d.since then f.debuffUptime[s]=(f.debuffUptime[s]or 0)+(n-d.since)end if d and d.historyEntry and not d.historyEntry.removed then d.historyEntry.removed=n end f.debuffs[s]={since=n,targetGUID=dG}local e={applied=n}table.insert(h,e)f.debuffs[s].historyEntry=e elseif se=="SPELL_AURA_REMOVED"then if d and d.since then f.debuffUptime[s]=(f.debuffUptime[s]or 0)+(n-d.since)end if d and d.historyEntry and not d.historyEntry.removed then d.historyEntry.removed=n end f.debuffs[s]=nil end end
function module.Analyze(a,f,c)local m={}local i={}local sc=100 if c.duration<15 then utils.AddIssue(i,"Walka zbyt krotka.")return{score=0,metrics=m,issues=i}end local function AM(l,s,v,p,st,it,pen)table.insert(m,{label=l,spellId=s,valueText=v or"",percent=p,status=st or"info"})utils.AddIssue(i,it)if pen and pen>0 then sc=utils.Clamp(sc-pen,0,100)end end local srUp=utils.SafePercent(f.buffUptime[SPELL_SAVAGE_ROAR]or 0,c.duration)local srSt=utils.StatusForPercent(srUp,0.95,0.85)AM("Savage Roar uptime",SPELL_SAVAGE_ROAR,utils.FormatPercent(srUp),srUp,srSt,srSt=="bad"and"Niski uptime Savage Roar!"or(srSt=="warn"and"SR moglby byc wyzszy."or nil),srSt=="bad"and 15 or(srSt=="warn"and 8 or 0))local rakeUp=utils.SafePercent(f.debuffUptime[SPELL_RAKE]or 0,c.duration)local rakeSt=utils.StatusForPercent(rakeUp,0.90,0.75)AM("Rake uptime",SPELL_RAKE,utils.FormatPercent(rakeUp),rakeUp,rakeSt,rakeSt=="bad"and"Niski uptime Rake."or(rakeSt=="warn"and"Rake moglby byc wyzszy."or nil),rakeSt=="bad"and 10 or(rakeSt=="warn"and 5 or 0))local ripUp=utils.SafePercent(f.debuffUptime[SPELL_RIP]or 0,c.duration)local ripSt=utils.StatusForPercent(ripUp,0.85,0.70)AM("Rip uptime",SPELL_RIP,utils.FormatPercent(ripUp),ripUp,ripSt,ripSt=="bad"and"Niski uptime Rip."or(ripSt=="warn"and"Rip moglby byc wyzszy."or nil),ripSt=="bad"and 12 or(ripSt=="warn"and 6 or 0))local tf=f.spells[SPELL_TIGERS_FURY]or 0 local expTF=utils.ExpectedUses(c.duration,COOLDOWN_TIGERS_FURY,10)if expTF>0 then local tfP=utils.SafePercent(tf,expTF)local tfSt=utils.StatusForPercent(tfP,0.85,0.70)AM("Tiger's Fury uzycia",SPELL_TIGERS_FURY,string.format("%d/%d",tf,expTF),math.min(tfP or 0,1),tfSt,tfSt=="bad"and"Za malo Tiger's Fury."or(tfSt=="warn"and"TF uzywany zbyt rzadko."or nil),tfSt=="bad"and 10 or(tfSt=="warn"and 5 or 0))end if f.rotation and f.rotation.totalCasts>0 then local rS=module.GetRotationScore(f)if rS then local rA=rS.accuracy or 0 local rSt=utils.StatusForPercent(rA,0.85,0.70)AM("Dokladnosc rotacji (APL)",nil,string.format("%.0f%% (%d/%d)",rA*100,rS.optimalCasts,rS.totalCasts),rA,rSt,rSt=="bad"and"Niska dokladnosc."or(rSt=="warn"and"Srednia dokladnosc."or nil),rSt=="bad"and 10 or(rSt=="warn"and 5 or 0))if rS.mistakes and #rS.mistakes>0 then local mC={}for _,mk in ipairs(rS.mistakes)do mC[mk.reason or"Unknown"]=(mC[mk.reason or"Unknown"]or 0)+1 end local sM={}for r,ct in pairs(mC)do table.insert(sM,{reason=r,count=ct})end table.sort(sM,function(x,y)return x.count>y.count end)for j=1,math.min(3,#sM)do local mk=sM[j]if mk.count>=2 then utils.AddIssue(i,string.format("Blad rotacji (%dx): %s",mk.count,mk.reason))end end end end end sc=utils.Clamp(sc,0,100)return{score=sc,metrics=m,issues=i}end
function module.GetLiveScore(a,f)if not f then return nil end local n=GetTime()local d=n-f.startTime if d<5 then return nil end return 100 end
local function CPB(s)if not s then return false,0 end for i=1,40 do local _,_,st,_,_,eT,_,_,_,aS=UnitBuff("player",i)if not aS then break end if aS==s then local r=eT and(eT-GetTime())or 0 return true,r end end return false,0 end
local function CTD(s)if not s or not UnitExists("target")then return false,0 end for i=1,40 do local _,_,_,_,_,eT,_,c,_,_,aS=UnitDebuff("target",i)if not aS then break end if aS==s and c=="player"then local r=eT and(eT-GetTime())or 0 return true,r end end return false,0 end
local function GCP()return UnitPower("player",4)or 0 end
local function GEnergy()return UnitPower("player",3)or 0 end
function module.GetLiveAdvice(a,f)if not f then return""end local n=GetTime()local d=n-f.startTime local cp=GCP()local energy=GEnergy()local hasSR,srR=CPB(SPELL_SAVAGE_ROAR)if not hasSR and cp>=1 then return"Savage Roar! (brak)"end if hasSR and srR>0 and srR<3 and cp>=1 then return"Odswiez Savage Roar!"end if utils.IsSpellReady(SPELL_TIGERS_FURY)and energy<35 then return"Tiger's Fury! (niska energia)"end if UnitExists("target")then local hasRip,ripR=CTD(SPELL_RIP)if cp>=5 and(not hasRip or(ripR>0 and ripR<3))then return"Rip! (5 CP)"end local hasRake,rakeR=CTD(SPELL_RAKE)if not hasRake and d>2 then return"Naloz Rake!"end if hasRake and rakeR>0 and rakeR<3 then return"Odswiez Rake!"end end if cp>=5 then return"Ferocious Bite! (5 CP)"end return""end
function module.GetAdviceSpellIcon(a,f)if not f then return nil end local n=GetTime()local d=n-f.startTime local cp=GCP()local energy=GEnergy()local hasSR,srR=CPB(SPELL_SAVAGE_ROAR)if not hasSR and cp>=1 then return SPELL_SAVAGE_ROAR end if hasSR and srR>0 and srR<3 and cp>=1 then return SPELL_SAVAGE_ROAR end if utils.IsSpellReady(SPELL_TIGERS_FURY)and energy<35 then return SPELL_TIGERS_FURY end if UnitExists("target")then local hasRip,ripR=CTD(SPELL_RIP)if cp>=5 and(not hasRip or(ripR>0 and ripR<3))then return SPELL_RIP end local hasRake,rakeR=CTD(SPELL_RAKE)if not hasRake and d>2 then return SPELL_RAKE end if hasRake and rakeR>0 and rakeR<3 then return SPELL_RAKE end end if cp>=5 then return SPELL_FEROCIOUS_BITE end return nil end
local APL_PRIORITY={{id="sr_m",spellId=SPELL_SAVAGE_ROAR,name="Savage Roar",condition=function(s)return s.srMissing and s.cp>=1 end,priority=1,category="buff"},{id="tf",spellId=SPELL_TIGERS_FURY,name="Tiger's Fury",condition=function(s)return s.tfReady and s.energy<35 end,priority=2,category="cooldown"},{id="rip",spellId=SPELL_RIP,name="Rip",condition=function(s)return s.cp>=5 and(s.ripMissing or s.ripExpiring)end,priority=3,category="finisher"},{id="sr_r",spellId=SPELL_SAVAGE_ROAR,name="SR(refresh)",condition=function(s)return s.srExpiring and s.cp>=1 end,priority=4,category="buff"},{id="rake_m",spellId=SPELL_RAKE,name="Rake",condition=function(s)return s.rakeMissing and s.duration>2 end,priority=5,category="dot"},{id="rake_r",spellId=SPELL_RAKE,name="Rake(r)",condition=function(s)return s.rakeExpiring end,priority=6,category="dot"},{id="fb",spellId=SPELL_FEROCIOUS_BITE,name="Ferocious Bite",condition=function(s)return s.cp>=5 end,priority=7,category="finisher"},{id="shred",spellId=SPELL_SHRED,name="Shred",condition=function(s)return true end,priority=8,category="builder"}}
local function GCS(a,f)local s={duration=0,cp=0,energy=0,srMissing=false,srExpiring=false,tfReady=false,ripMissing=false,ripExpiring=false,rakeMissing=false,rakeExpiring=false}if not f then return s end local n=GetTime()s.duration=n-(f.startTime or n)s.cp=GCP()s.energy=GEnergy()local hasSR,srR=CPB(SPELL_SAVAGE_ROAR)s.srMissing=not hasSR s.srExpiring=hasSR and srR>0 and srR<3 s.tfReady=utils.IsSpellReady(SPELL_TIGERS_FURY)if UnitExists("target")and s.duration>2 then local hasRip,ripR=CTD(SPELL_RIP)s.ripMissing=not hasRip s.ripExpiring=hasRip and ripR>0 and ripR<3 local hasRake,rakeR=CTD(SPELL_RAKE)s.rakeMissing=not hasRake s.rakeExpiring=hasRake and rakeR>0 and rakeR<3 end return s end
function module.GetNextAPLAction(a,f)local s=GCS(a,f)for _,act in ipairs(APL_PRIORITY)do if act.condition(s)then return act end end return APL_PRIORITY[#APL_PRIORITY]end
function module.GetAPLPriorityList()return APL_PRIORITY end
function module.GetRotationState(a,f)return GCS(a,f)end
function module.EvaluateCast(a,f,sid,ts)local nA=module.GetNextAPLAction(a,f)if not nA then return nil end local isO=(nA.spellId==sid)local pen=0 local rsn=""if not isO then local cP=nil for _,act in ipairs(APL_PRIORITY)do if act.spellId==sid then cP=act.priority break end end if cP then pen=math.abs(nA.priority-cP)*2 rsn=string.format("Powinienes: %s",nA.name)else pen=5 rsn="Spell poza APL"end end return{isOptimal=isO,penalty=pen,reason=rsn,expectedSpell=nA.spellId,expectedName=nA.name,actualSpell=sid}end
function module.RecordCastEvaluation(f,ev,ts)if not f.rotation then return end f.rotation.totalCasts=f.rotation.totalCasts+1 if ev.isOptimal then f.rotation.optimalCasts=f.rotation.optimalCasts+1 else f.rotation.suboptimalCasts=f.rotation.suboptimalCasts+1 f.rotation.penaltySum=f.rotation.penaltySum+ev.penalty table.insert(f.rotation.mistakes,{timestamp=ts,reason=ev.reason,penalty=ev.penalty,expected=ev.expectedName})end end
function module.GetRotationScore(f)if not f.rotation or f.rotation.totalCasts==0 then return nil end return{accuracy=f.rotation.optimalCasts/f.rotation.totalCasts,totalCasts=f.rotation.totalCasts,optimalCasts=f.rotation.optimalCasts,suboptimalCasts=f.rotation.suboptimalCasts,mistakes=f.rotation.mistakes,penaltySum=f.rotation.penaltySum}end
Analyzer:RegisterClassModule(module.class,module)
