local _,Analyzer=...if not Analyzer then return end
local module={}
local utils=Analyzer.utils
module.name="Hunter - Survival"
module.class="HUNTER"
module.specKey="survival"
module.specIndex=3
module.specId=255
local SPELL_EXPLOSIVE_SHOT=53301
local SPELL_BLACK_ARROW=3674
local SPELL_ARCANE_SHOT=3044
local SPELL_COBRA_SHOT=77767
local SPELL_KILL_SHOT=53351
local SPELL_SERPENT_STING=1978
local SPELL_LOCK_AND_LOAD=56453
local SPELL_RAPID_FIRE=3045
local SPELL_A_MURDER_OF_CROWS=131894
local SPELL_GLAIVE_TOSS=117050
local SPELL_BARRAGE=120360
local SPELL_DIRE_BEAST=120679
local COOLDOWN_BLACK_ARROW=24
local COOLDOWN_EXPLOSIVE_SHOT=6
local COOLDOWN_RAPID_FIRE=180
local COOLDOWN_CROWS=120
local SOUND_KEY_LOCK_AND_LOAD="lockAndLoad"
local SOUND_KEY_RAPID_FIRE="rapidFire"
local SOUND_KEY_KILL_SHOT="killShot"
local TRACKED_BUFFS={[SPELL_LOCK_AND_LOAD]=true,[SPELL_RAPID_FIRE]=true}
local TRACKED_DEBUFFS={[SPELL_SERPENT_STING]=true,[SPELL_BLACK_ARROW]=true}
local TRACKED_CASTS={[SPELL_EXPLOSIVE_SHOT]=true,[SPELL_BLACK_ARROW]=true,[SPELL_ARCANE_SHOT]=true,[SPELL_COBRA_SHOT]=true,[SPELL_KILL_SHOT]=true,[SPELL_RAPID_FIRE]=true,[SPELL_A_MURDER_OF_CROWS]=true,[SPELL_GLAIVE_TOSS]=true,[SPELL_BARRAGE]=true,[SPELL_DIRE_BEAST]=true,[SPELL_SERPENT_STING]=true}
local function EH(c,s)c[s]=c[s]or{}return c[s]end
function module.SupportsSpec(a)if a.player.class~=module.class then return false end if a.player.specId==module.specId then return true end local sk=utils.NormalizeSpecKey(a.player.specName)if sk==module.specKey then return true end if a.player.specIndex==module.specIndex then return true end return false end
function module.OnPlayerInit(a)if a.player.class~=module.class then return end if a.player.specName~="Unknown"then return end if IsSpellKnown and IsSpellKnown(SPELL_EXPLOSIVE_SHOT)and IsSpellKnown(SPELL_BLACK_ARROW)then a.player.specName="Survival"a.player.specId=a.player.specId or module.specId a.player.specIndex=a.player.specIndex or module.specIndex end end
function module.GetDefaultSettings()return{sounds={[SOUND_KEY_LOCK_AND_LOAD]={enabled=true,sound="Sound\\Interface\\RaidWarning.ogg"},[SOUND_KEY_RAPID_FIRE]={enabled=true,sound="Sound\\Interface\\MapPing.ogg"},[SOUND_KEY_KILL_SHOT]={enabled=true,sound="Sound\\Interface\\RaidWarning.ogg"}}}end
function module.GetSoundOptions()return{{key=SOUND_KEY_LOCK_AND_LOAD,label="Lock and Load Proc"},{key=SOUND_KEY_RAPID_FIRE,label="Rapid Fire Ready"},{key=SOUND_KEY_KILL_SHOT,label="Kill Shot Available"}}end
function module.IsTrackedBuffSpell(s)return TRACKED_BUFFS[s]==true end
function module.IsTrackedDebuffSpell(s)return TRACKED_DEBUFFS[s]==true end
function module.IsTrackedCast(s)return TRACKED_CASTS[s]==true end
function module.ShouldRecordCast(e)if not e or not e.spellId then return false end return TRACKED_CASTS[e.spellId]==true end
function module.GetProcInfo(s)if s==SPELL_LOCK_AND_LOAD then return{soundKey=SOUND_KEY_LOCK_AND_LOAD,priority=3}end return nil end
function module.InitFight(_,f)f.procs={lockAndLoadProcs=0,lockAndLoadConsumed=0}f.counts={explosiveShotCasts=0,killShotCasts=0}f.cooldowns={rapidFireLast=0,crowsLast=0}f.castLog={}f.buffHistory={}f.debuffHistory={}f.rotation={totalCasts=0,optimalCasts=0,suboptimalCasts=0,mistakes={},penaltySum=0}end
function module.TrackSpellCast(a,s,t)local f=a.fight if not f or not TRACKED_CASTS[s]then return end local n=utils.NormalizeTimestamp(t)f.spells[s]=(f.spells[s]or 0)+1 table.insert(f.castLog,{spellId=s,timestamp=n})if s==SPELL_EXPLOSIVE_SHOT then f.counts.explosiveShotCasts=f.counts.explosiveShotCasts+1 local b=f.buffs[SPELL_LOCK_AND_LOAD]if b and(b.stacks or 0)>0 then f.procs.lockAndLoadConsumed=f.procs.lockAndLoadConsumed+1 b.stacks=(b.stacks or 1)-1 if b.stacks<=0 then b.stacks=nil end end elseif s==SPELL_KILL_SHOT then f.counts.killShotCasts=f.counts.killShotCasts+1 a:AddEventLog(n,"Kill Shot",s)elseif s==SPELL_RAPID_FIRE then f.cooldowns.rapidFireLast=n a:AddTimelineEvent(s,n,"cooldown")a:AddEventLog(n,"Rapid Fire",s)elseif s==SPELL_BLACK_ARROW then a:AddEventLog(n,"Black Arrow",s)elseif s==SPELL_A_MURDER_OF_CROWS then f.cooldowns.crowsLast=n a:AddTimelineEvent(s,n,"cooldown")a:AddEventLog(n,"A Murder of Crows",s)end local cS={[SPELL_EXPLOSIVE_SHOT]=true,[SPELL_BLACK_ARROW]=true,[SPELL_ARCANE_SHOT]=true,[SPELL_COBRA_SHOT]=true,[SPELL_KILL_SHOT]=true}if cS[s]and f.rotation then local ev=module.EvaluateCast(a,f,s,n)if ev then module.RecordCastEvaluation(f,ev,n)end end end
function module.TrackAura(a,se,s,am,t)local f=a.fight if not f then return end local n=utils.NormalizeTimestamp(t)if se=="SPELL_AURA_APPLIED"or se=="SPELL_AURA_APPLIED_DOSE"or se=="SPELL_AURA_REFRESH"then local st=am or 1 local b=f.buffs[s]local isR=(se=="SPELL_AURA_REFRESH")if b and isR and b.since then f.buffUptime[s]=(f.buffUptime[s]or 0)+(n-b.since)end if not b then b={stacks=st,since=n}f.buffs[s]=b else b.stacks=st b.since=b.since or n end if isR then b.since=n end local h=EH(f.buffHistory,s)if isR and b.historyEntry and not b.historyEntry.removed then b.historyEntry.removed=n end if not b.historyEntry or isR then b.historyEntry={applied=n}table.insert(h,b.historyEntry)end if s==SPELL_LOCK_AND_LOAD then if not isR then f.procs.lockAndLoadProcs=f.procs.lockAndLoadProcs+1 a:AddTimelineEvent(s,n,"proc")end a:PlayAlertSound(SOUND_KEY_LOCK_AND_LOAD,n)end elseif se=="SPELL_AURA_REMOVED"then local b=f.buffs[s]if b then if b.since then f.buffUptime[s]=(f.buffUptime[s]or 0)+(n-b.since)end if b.historyEntry and not b.historyEntry.removed then b.historyEntry.removed=n end end f.buffs[s]=nil end end
function module.TrackDebuff(a,se,s,dG,dN,t)local f=a.fight if not f or not TRACKED_DEBUFFS[s]then return end local n=utils.NormalizeTimestamp(t)if not f.primaryTargetGUID then f.primaryTargetGUID=dG end if dG and f.primaryTargetGUID and dG~=f.primaryTargetGUID then return end if dG then f.targets[dG]=true end local d=f.debuffs[s]local h=EH(f.debuffHistory,s)if se=="SPELL_AURA_APPLIED"then f.debuffs[s]={since=n,targetGUID=dG}local e={applied=n}table.insert(h,e)f.debuffs[s].historyEntry=e elseif se=="SPELL_AURA_REFRESH"then if d and d.since then f.debuffUptime[s]=(f.debuffUptime[s]or 0)+(n-d.since)end if d and d.historyEntry and not d.historyEntry.removed then d.historyEntry.removed=n end f.debuffs[s]={since=n,targetGUID=dG}local e={applied=n}table.insert(h,e)f.debuffs[s].historyEntry=e elseif se=="SPELL_AURA_REMOVED"then if d and d.since then f.debuffUptime[s]=(f.debuffUptime[s]or 0)+(n-d.since)end if d and d.historyEntry and not d.historyEntry.removed then d.historyEntry.removed=n end f.debuffs[s]=nil end end
function module.Analyze(a,f,c)local m={}local i={}local sc=100 if c.duration<15 then utils.AddIssue(i,"Walka zbyt krotka.")return{score=0,metrics=m,issues=i}end local function AM(l,s,v,p,st,it,pen)table.insert(m,{label=l,spellId=s,valueText=v or"",percent=p,status=st or"info"})utils.AddIssue(i,it)if pen and pen>0 then sc=utils.Clamp(sc-pen,0,100)end end local ssUp=utils.SafePercent(f.debuffUptime[SPELL_SERPENT_STING]or 0,c.duration)local ssSt=utils.StatusForPercent(ssUp,0.90,0.75)AM("Serpent Sting uptime",SPELL_SERPENT_STING,utils.FormatPercent(ssUp),ssUp,ssSt,ssSt=="bad"and"Niski uptime Serpent Sting."or(ssSt=="warn"and"SS moglby byc wyzszy."or nil),ssSt=="bad"and 10 or(ssSt=="warn"and 5 or 0))local baUp=utils.SafePercent(f.debuffUptime[SPELL_BLACK_ARROW]or 0,c.duration)local baSt=utils.StatusForPercent(baUp,0.85,0.70)AM("Black Arrow uptime",SPELL_BLACK_ARROW,utils.FormatPercent(baUp),baUp,baSt,baSt=="bad"and"Niski uptime Black Arrow."or(baSt=="warn"and"BA moglby byc wyzszy."or nil),baSt=="bad"and 12 or(baSt=="warn"and 6 or 0))local es=f.spells[SPELL_EXPLOSIVE_SHOT]or 0 local expES=math.floor(c.duration/COOLDOWN_EXPLOSIVE_SHOT)if expES>0 then local esP=utils.SafePercent(es,expES)local esSt=utils.StatusForPercent(esP,0.85,0.70)AM("Explosive Shot uzycia",SPELL_EXPLOSIVE_SHOT,string.format("%d/%d",es,expES),math.min(esP or 0,1),esSt,esSt=="bad"and"Za malo Explosive Shot."or(esSt=="warn"and"ES uzywany zbyt rzadko."or nil),esSt=="bad"and 10 or(esSt=="warn"and 5 or 0))end local lalP=f.procs.lockAndLoadProcs or 0 local lalC=f.procs.lockAndLoadConsumed or 0 if lalP>0 then local lalU=utils.SafePercent(lalC,lalP*2)local lalSt=utils.StatusForPercent(lalU,0.85,0.70)AM("Lock and Load wykorzystanie",SPELL_LOCK_AND_LOAD,string.format("%s (%d/%d)",utils.FormatPercent(lalU),lalC,lalP*2),lalU,lalSt,lalSt=="bad"and"Za duzo L&L nie zuzyte."or(lalSt=="warn"and"Czesc L&L sie marnuje."or nil),lalSt=="bad"and 12 or(lalSt=="warn"and 6 or 0))end if f.rotation and f.rotation.totalCasts>0 then local rS=module.GetRotationScore(f)if rS then local rA=rS.accuracy or 0 local rSt=utils.StatusForPercent(rA,0.85,0.70)AM("Dokladnosc rotacji (APL)",nil,string.format("%.0f%% (%d/%d)",rA*100,rS.optimalCasts,rS.totalCasts),rA,rSt,rSt=="bad"and"Niska dokladnosc."or(rSt=="warn"and"Srednia dokladnosc."or nil),rSt=="bad"and 10 or(rSt=="warn"and 5 or 0))if rS.mistakes and #rS.mistakes>0 then local mC={}for _,mk in ipairs(rS.mistakes)do mC[mk.reason or"Unknown"]=(mC[mk.reason or"Unknown"]or 0)+1 end local sM={}for r,ct in pairs(mC)do table.insert(sM,{reason=r,count=ct})end table.sort(sM,function(x,y)return x.count>y.count end)for j=1,math.min(3,#sM)do local mk=sM[j]if mk.count>=2 then utils.AddIssue(i,string.format("Blad rotacji (%dx): %s",mk.count,mk.reason))end end end end end sc=utils.Clamp(sc,0,100)return{score=sc,metrics=m,issues=i}end
function module.GetLiveScore(a,f)if not f then return nil end local n=GetTime()local d=n-f.startTime if d<5 then return nil end return 100 end
local function CPB(s)if not s then return false,0 end for i=1,40 do local _,_,st,_,_,_,_,_,_,aS=UnitBuff("player",i)if not aS then break end if aS==s then return true,st or 1 end end return false,0 end
local function CTD(s)if not s or not UnitExists("target")then return false,0 end for i=1,40 do local _,_,_,_,_,eT,_,c,_,_,aS=UnitDebuff("target",i)if not aS then break end if aS==s and c=="player"then local r=eT and(eT-GetTime())or 0 return true,r end end return false,0 end
local function TargetLowHP()if not UnitExists("target")then return false end local hp=UnitHealth("target")local maxHP=UnitHealthMax("target")if maxHP==0 then return false end return(hp/maxHP)<0.20 end
function module.GetLiveAdvice(a,f)if not f then return""end local n=GetTime()local d=n-f.startTime if TargetLowHP()and utils.IsSpellReady(SPELL_KILL_SHOT)then return"Kill Shot! Target nisko!"end local hasLaL,lalS=CPB(SPELL_LOCK_AND_LOAD)if hasLaL and lalS>0 then return string.format("Explosive Shot! (L&L x%d)",lalS)end if utils.IsSpellReady(SPELL_EXPLOSIVE_SHOT)then return"Explosive Shot!"end if UnitExists("target")then local hasBA,baR=CTD(SPELL_BLACK_ARROW)if not hasBA and d>2 then return"Naloz Black Arrow!"end if hasBA and baR>0 and baR<4 then return"Black Arrow wygasa!"end local hasSS,ssR=CTD(SPELL_SERPENT_STING)if not hasSS and d>2 then return"Naloz Serpent Sting!"end if hasSS and ssR>0 and ssR<4 then return"Serpent Sting wygasa!"end end if utils.IsSpellReady(SPELL_RAPID_FIRE)and d>10 then return"Rapid Fire gotowe!"end return""end
function module.GetAdviceSpellIcon(a,f)if not f then return nil end local n=GetTime()local d=n-f.startTime if TargetLowHP()and utils.IsSpellReady(SPELL_KILL_SHOT)then return SPELL_KILL_SHOT end local hasLaL,lalS=CPB(SPELL_LOCK_AND_LOAD)if hasLaL and lalS>0 then return SPELL_EXPLOSIVE_SHOT end if utils.IsSpellReady(SPELL_EXPLOSIVE_SHOT)then return SPELL_EXPLOSIVE_SHOT end if UnitExists("target")then local hasBA,baR=CTD(SPELL_BLACK_ARROW)if not hasBA and d>2 then return SPELL_BLACK_ARROW end if hasBA and baR>0 and baR<4 then return SPELL_BLACK_ARROW end local hasSS,ssR=CTD(SPELL_SERPENT_STING)if not hasSS and d>2 then return SPELL_SERPENT_STING end if hasSS and ssR>0 and ssR<4 then return SPELL_SERPENT_STING end end if utils.IsSpellReady(SPELL_RAPID_FIRE)and d>10 then return SPELL_RAPID_FIRE end return nil end
local APL_PRIORITY={{id="ks",spellId=SPELL_KILL_SHOT,name="Kill Shot",condition=function(s)return s.targetLow and s.ksReady end,priority=1,category="execute"},{id="es_lal",spellId=SPELL_EXPLOSIVE_SHOT,name="ES(L&L)",condition=function(s)return s.lockAndLoad end,priority=2,category="proc"},{id="es",spellId=SPELL_EXPLOSIVE_SHOT,name="Explosive Shot",condition=function(s)return s.esReady end,priority=3,category="core"},{id="ba_m",spellId=SPELL_BLACK_ARROW,name="Black Arrow",condition=function(s)return s.baMissing and s.duration>2 end,priority=4,category="dot"},{id="ss_m",spellId=SPELL_SERPENT_STING,name="Serpent Sting",condition=function(s)return s.ssMissing and s.duration>2 end,priority=5,category="dot"},{id="ba_r",spellId=SPELL_BLACK_ARROW,name="BA(refresh)",condition=function(s)return s.baExpiring end,priority=6,category="dot"},{id="ss_r",spellId=SPELL_SERPENT_STING,name="SS(refresh)",condition=function(s)return s.ssExpiring end,priority=7,category="dot"},{id="as",spellId=SPELL_ARCANE_SHOT,name="Arcane Shot",condition=function(s)return s.focus>=60 end,priority=8,category="dump"},{id="cs",spellId=SPELL_COBRA_SHOT,name="Cobra Shot",condition=function(s)return true end,priority=9,category="builder"}}
local function GCS(a,f)local s={duration=0,targetLow=false,ksReady=false,lockAndLoad=false,esReady=false,baMissing=false,baExpiring=false,ssMissing=false,ssExpiring=false,focus=0}if not f then return s end local n=GetTime()s.duration=n-(f.startTime or n)s.targetLow=TargetLowHP()s.ksReady=utils.IsSpellReady(SPELL_KILL_SHOT)local hasLaL,lalS=CPB(SPELL_LOCK_AND_LOAD)s.lockAndLoad=hasLaL and lalS>0 s.esReady=utils.IsSpellReady(SPELL_EXPLOSIVE_SHOT)s.focus=UnitPower("player",2)or 0 if UnitExists("target")and s.duration>2 then local hasBA,baR=CTD(SPELL_BLACK_ARROW)s.baMissing=not hasBA s.baExpiring=hasBA and baR>0 and baR<4 local hasSS,ssR=CTD(SPELL_SERPENT_STING)s.ssMissing=not hasSS s.ssExpiring=hasSS and ssR>0 and ssR<4 end return s end
function module.GetNextAPLAction(a,f)local s=GCS(a,f)for _,act in ipairs(APL_PRIORITY)do if act.condition(s)then return act end end return APL_PRIORITY[#APL_PRIORITY]end
function module.GetAPLPriorityList()return APL_PRIORITY end
function module.GetRotationState(a,f)return GCS(a,f)end
function module.EvaluateCast(a,f,sid,ts)local nA=module.GetNextAPLAction(a,f)if not nA then return nil end local isO=(nA.spellId==sid)local pen=0 local rsn=""if not isO then local cP=nil for _,act in ipairs(APL_PRIORITY)do if act.spellId==sid then cP=act.priority break end end if cP then pen=math.abs(nA.priority-cP)*2 rsn=string.format("Powinienes: %s",nA.name)else pen=5 rsn="Spell poza APL"end end return{isOptimal=isO,penalty=pen,reason=rsn,expectedSpell=nA.spellId,expectedName=nA.name,actualSpell=sid}end
function module.RecordCastEvaluation(f,ev,ts)if not f.rotation then return end f.rotation.totalCasts=f.rotation.totalCasts+1 if ev.isOptimal then f.rotation.optimalCasts=f.rotation.optimalCasts+1 else f.rotation.suboptimalCasts=f.rotation.suboptimalCasts+1 f.rotation.penaltySum=f.rotation.penaltySum+ev.penalty table.insert(f.rotation.mistakes,{timestamp=ts,reason=ev.reason,penalty=ev.penalty,expected=ev.expectedName})end end
function module.GetRotationScore(f)if not f.rotation or f.rotation.totalCasts==0 then return nil end return{accuracy=f.rotation.optimalCasts/f.rotation.totalCasts,totalCasts=f.rotation.totalCasts,optimalCasts=f.rotation.optimalCasts,suboptimalCasts=f.rotation.suboptimalCasts,mistakes=f.rotation.mistakes,penaltySum=f.rotation.penaltySum}end
Analyzer:RegisterClassModule(module.class,module)
