local _,Analyzer=...if not Analyzer then return end
local module={}
local utils=Analyzer.utils
module.name="Mage - Arcane"
module.class="MAGE"
module.specKey="arcane"
module.specIndex=1
module.specId=62
local SPELL_ARCANE_BLAST=30451
local SPELL_ARCANE_MISSILES=5143
local SPELL_ARCANE_MISSILES_BUFF=79683
local SPELL_ARCANE_BARRAGE=44425
local SPELL_ARCANE_POWER=12042
local SPELL_EVOCATION=12051
local SPELL_PRESENCE_OF_MIND=12043
local SPELL_NETHER_TEMPEST=114923
local SPELL_ARCANE_CHARGE=36032
local SPELL_RUNE_OF_POWER=116011
local COOLDOWN_ARCANE_POWER=90
local COOLDOWN_EVOCATION=120
local COOLDOWN_POM=90
local SOUND_KEY_ARCANE_MISSILES="arcaneMissiles"
local SOUND_KEY_ARCANE_POWER="arcanePower"
local TRACKED_BUFFS={[SPELL_ARCANE_MISSILES_BUFF]=true,[SPELL_ARCANE_POWER]=true,[SPELL_PRESENCE_OF_MIND]=true,[SPELL_RUNE_OF_POWER]=true}
local TRACKED_DEBUFFS={[SPELL_NETHER_TEMPEST]=true}
local TRACKED_CASTS={[SPELL_ARCANE_BLAST]=true,[SPELL_ARCANE_MISSILES]=true,[SPELL_ARCANE_BARRAGE]=true,[SPELL_ARCANE_POWER]=true,[SPELL_EVOCATION]=true,[SPELL_PRESENCE_OF_MIND]=true,[SPELL_NETHER_TEMPEST]=true}
local function EH(c,s)c[s]=c[s]or{}return c[s]end
function module.SupportsSpec(a)if a.player.class~=module.class then return false end if a.player.specId==module.specId then return true end local sk=utils.NormalizeSpecKey(a.player.specName)if sk==module.specKey then return true end if a.player.specIndex==module.specIndex then return true end return false end
function module.OnPlayerInit(a)if a.player.class~=module.class then return end if a.player.specName~="Unknown"then return end if IsSpellKnown and IsSpellKnown(SPELL_ARCANE_BLAST)and IsSpellKnown(SPELL_ARCANE_BARRAGE)then a.player.specName="Arcane"a.player.specId=a.player.specId or module.specId a.player.specIndex=a.player.specIndex or module.specIndex end end
function module.GetDefaultSettings()return{sounds={[SOUND_KEY_ARCANE_MISSILES]={enabled=true,sound="Sound\\Interface\\RaidWarning.ogg"},[SOUND_KEY_ARCANE_POWER]={enabled=true,sound="Sound\\Interface\\MapPing.ogg"}}}end
function module.GetSoundOptions()return{{key=SOUND_KEY_ARCANE_MISSILES,label="Arcane Missiles Proc"},{key=SOUND_KEY_ARCANE_POWER,label="Arcane Power Ready"}}end
function module.IsTrackedBuffSpell(s)return TRACKED_BUFFS[s]==true end
function module.IsTrackedDebuffSpell(s)return TRACKED_DEBUFFS[s]==true end
function module.IsTrackedCast(s)return TRACKED_CASTS[s]==true end
function module.ShouldRecordCast(e)if not e or not e.spellId then return false end return TRACKED_CASTS[e.spellId]==true end
function module.GetProcInfo(s)if s==SPELL_ARCANE_MISSILES_BUFF then return{soundKey=SOUND_KEY_ARCANE_MISSILES,priority=3}end return nil end
function module.InitFight(_,f)f.procs={arcaneMissilesProcs=0,arcaneMissilesConsumed=0}f.counts={arcaneBlastCasts=0,arcaneBarrageCasts=0,highChargeBarrages=0}f.cooldowns={arcanePowerLast=0,evocationLast=0,pomLast=0}f.castLog={}f.buffHistory={}f.debuffHistory={}f.rotation={totalCasts=0,optimalCasts=0,suboptimalCasts=0,mistakes={},penaltySum=0}f.arcaneCharges=0 end
function module.TrackSpellCast(a,s,t)local f=a.fight if not f or not TRACKED_CASTS[s]then return end local n=utils.NormalizeTimestamp(t)f.spells[s]=(f.spells[s]or 0)+1 table.insert(f.castLog,{spellId=s,timestamp=n})if s==SPELL_ARCANE_BLAST then f.counts.arcaneBlastCasts=f.counts.arcaneBlastCasts+1 f.arcaneCharges=math.min((f.arcaneCharges or 0)+1,4)elseif s==SPELL_ARCANE_MISSILES then local b=f.buffs[SPELL_ARCANE_MISSILES_BUFF]if b and(b.stacks or 0)>0 then f.procs.arcaneMissilesConsumed=f.procs.arcaneMissilesConsumed+1 b.consumed=true b.stacks=0 end elseif s==SPELL_ARCANE_BARRAGE then f.counts.arcaneBarrageCasts=f.counts.arcaneBarrageCasts+1 if(f.arcaneCharges or 0)>=4 then f.counts.highChargeBarrages=f.counts.highChargeBarrages+1 end f.arcaneCharges=0 elseif s==SPELL_ARCANE_POWER then f.cooldowns.arcanePowerLast=n a:AddTimelineEvent(s,n,"cooldown")a:AddEventLog(n,"Arcane Power",s)elseif s==SPELL_EVOCATION then f.cooldowns.evocationLast=n a:AddTimelineEvent(s,n,"cooldown")a:AddEventLog(n,"Evocation",s)f.arcaneCharges=0 elseif s==SPELL_PRESENCE_OF_MIND then f.cooldowns.pomLast=n a:AddEventLog(n,"Presence of Mind",s)end local cS={[SPELL_ARCANE_BLAST]=true,[SPELL_ARCANE_MISSILES]=true,[SPELL_ARCANE_BARRAGE]=true,[SPELL_NETHER_TEMPEST]=true}if cS[s]and f.rotation then local ev=module.EvaluateCast(a,f,s,n)if ev then module.RecordCastEvaluation(f,ev,n)end end end
function module.TrackAura(a,se,s,am,t)local f=a.fight if not f then return end local n=utils.NormalizeTimestamp(t)if se=="SPELL_AURA_APPLIED"or se=="SPELL_AURA_APPLIED_DOSE"or se=="SPELL_AURA_REFRESH"then local st=am or 1 local b=f.buffs[s]local isR=(se=="SPELL_AURA_REFRESH")if b and isR and b.since then f.buffUptime[s]=(f.buffUptime[s]or 0)+(n-b.since)end if not b then b={stacks=st,since=n}f.buffs[s]=b else b.stacks=st b.since=b.since or n end if isR then b.since=n end local h=EH(f.buffHistory,s)if isR and b.historyEntry and not b.historyEntry.removed then b.historyEntry.removed=n end if not b.historyEntry or isR then b.historyEntry={applied=n}table.insert(h,b.historyEntry)end if s==SPELL_ARCANE_MISSILES_BUFF then if not isR then f.procs.arcaneMissilesProcs=f.procs.arcaneMissilesProcs+1 a:AddTimelineEvent(s,n,"proc")end a:PlayAlertSound(SOUND_KEY_ARCANE_MISSILES,n)elseif s==SPELL_ARCANE_CHARGE then f.arcaneCharges=st end elseif se=="SPELL_AURA_REMOVED"then local b=f.buffs[s]if b then if b.since then f.buffUptime[s]=(f.buffUptime[s]or 0)+(n-b.since)end if b.historyEntry and not b.historyEntry.removed then b.historyEntry.removed=n end end f.buffs[s]=nil if s==SPELL_ARCANE_CHARGE then f.arcaneCharges=0 end end end
function module.TrackDebuff(a,se,s,dG,dN,t)local f=a.fight if not f or not TRACKED_DEBUFFS[s]then return end local n=utils.NormalizeTimestamp(t)if not f.primaryTargetGUID then f.primaryTargetGUID=dG end if dG and f.primaryTargetGUID and dG~=f.primaryTargetGUID then return end if dG then f.targets[dG]=true end local d=f.debuffs[s]local h=EH(f.debuffHistory,s)if se=="SPELL_AURA_APPLIED"then f.debuffs[s]={since=n,targetGUID=dG}local e={applied=n}table.insert(h,e)f.debuffs[s].historyEntry=e elseif se=="SPELL_AURA_REFRESH"then if d and d.since then f.debuffUptime[s]=(f.debuffUptime[s]or 0)+(n-d.since)end if d and d.historyEntry and not d.historyEntry.removed then d.historyEntry.removed=n end f.debuffs[s]={since=n,targetGUID=dG}local e={applied=n}table.insert(h,e)f.debuffs[s].historyEntry=e elseif se=="SPELL_AURA_REMOVED"then if d and d.since then f.debuffUptime[s]=(f.debuffUptime[s]or 0)+(n-d.since)end if d and d.historyEntry and not d.historyEntry.removed then d.historyEntry.removed=n end f.debuffs[s]=nil end end
function module.Analyze(a,f,c)local m={}local i={}local sc=100 if c.duration<15 then utils.AddIssue(i,"Walka zbyt krotka.")return{score=0,metrics=m,issues=i}end local function AM(l,s,v,p,st,it,pen)table.insert(m,{label=l,spellId=s,valueText=v or"",percent=p,status=st or"info"})utils.AddIssue(i,it)if pen and pen>0 then sc=utils.Clamp(sc-pen,0,100)end end local ntUp=utils.SafePercent(f.debuffUptime[SPELL_NETHER_TEMPEST]or 0,c.duration)local ntSt=utils.StatusForPercent(ntUp,0.90,0.80)AM("Nether Tempest uptime",SPELL_NETHER_TEMPEST,utils.FormatPercent(ntUp),ntUp,ntSt,ntSt=="bad"and"Niski uptime Nether Tempest."or(ntSt=="warn"and"NT moglby byc wyzszy."or nil),ntSt=="bad"and 12 or(ntSt=="warn"and 6 or 0))local amP=f.procs.arcaneMissilesProcs or 0 local amC=f.procs.arcaneMissilesConsumed or 0 if amP>0 then local amU=utils.SafePercent(amC,amP)local amSt=utils.StatusForPercent(amU,0.85,0.70)AM("Arcane Missiles wykorzystanie",SPELL_ARCANE_MISSILES_BUFF,string.format("%s (%d/%d)",utils.FormatPercent(amU),amC,amP),amU,amSt,amSt=="bad"and"Za duzo AM nie zuzyte."or(amSt=="warn"and"Czesc AM sie marnuje."or nil),amSt=="bad"and 12 or(amSt=="warn"and 6 or 0))end local ap=f.spells[SPELL_ARCANE_POWER]or 0 local expAP=utils.ExpectedUses(c.duration,COOLDOWN_ARCANE_POWER,10)if expAP>0 then local apP=utils.SafePercent(ap,expAP)local apSt=utils.StatusForPercent(apP,0.80,0.60)AM("Arcane Power uzycia",SPELL_ARCANE_POWER,string.format("%d/%d",ap,expAP),math.min(apP or 0,1),apSt,apSt=="bad"and"Za malo Arcane Power."or(apSt=="warn"and"AP uzywany zbyt rzadko."or nil),apSt=="bad"and 10 or(apSt=="warn"and 5 or 0))end local barr=f.counts.arcaneBarrageCasts or 0 local highB=f.counts.highChargeBarrages or 0 if barr>0 then local hbP=utils.SafePercent(highB,barr)local hbSt=utils.StatusForPercent(hbP,0.85,0.70)AM("Barrage na 4 charges",SPELL_ARCANE_BARRAGE,string.format("%s (%d/%d)",utils.FormatPercent(hbP),highB,barr),hbP,hbSt,hbSt=="bad"and"Barrage przy niskich charges."or(hbSt=="warn"and"Czasem Barrage bez 4 charges."or nil),hbSt=="bad"and 10 or(hbSt=="warn"and 5 or 0))end if f.rotation and f.rotation.totalCasts>0 then local rS=module.GetRotationScore(f)if rS then local rA=rS.accuracy or 0 local rSt=utils.StatusForPercent(rA,0.85,0.70)AM("Dokladnosc rotacji (APL)",nil,string.format("%.0f%% (%d/%d)",rA*100,rS.optimalCasts,rS.totalCasts),rA,rSt,rSt=="bad"and"Niska dokladnosc."or(rSt=="warn"and"Srednia dokladnosc."or nil),rSt=="bad"and 10 or(rSt=="warn"and 5 or 0))if rS.mistakes and #rS.mistakes>0 then local mC={}for _,mk in ipairs(rS.mistakes)do mC[mk.reason or"Unknown"]=(mC[mk.reason or"Unknown"]or 0)+1 end local sM={}for r,ct in pairs(mC)do table.insert(sM,{reason=r,count=ct})end table.sort(sM,function(x,y)return x.count>y.count end)for j=1,math.min(3,#sM)do local mk=sM[j]if mk.count>=2 then utils.AddIssue(i,string.format("Blad rotacji (%dx): %s",mk.count,mk.reason))end end end end end sc=utils.Clamp(sc,0,100)return{score=sc,metrics=m,issues=i}end
function module.GetLiveScore(a,f)if not f then return nil end local n=GetTime()local d=n-f.startTime if d<5 then return nil end return 100 end
local function CPB(s)if not s then return false,0 end for i=1,40 do local _,_,st,_,_,_,_,_,_,aS=UnitBuff("player",i)if not aS then break end if aS==s then return true,st or 1 end end return false,0 end
local function CTD(s)if not s or not UnitExists("target")then return false,0 end for i=1,40 do local _,_,_,_,_,eT,_,c,_,_,aS=UnitDebuff("target",i)if not aS then break end if aS==s and c=="player"then local r=eT and(eT-GetTime())or 0 return true,r end end return false,0 end
local function GAC()local charges=0 for i=1,40 do local _,_,st,_,_,_,_,_,_,aS=UnitBuff("player",i)if not aS then break end if aS==SPELL_ARCANE_CHARGE then charges=st or 1 break end end return charges end
function module.GetLiveAdvice(a,f)if not f then return""end local n=GetTime()local d=n-f.startTime local hasAM,_=CPB(SPELL_ARCANE_MISSILES_BUFF)local charges=GAC()if hasAM and charges>=4 then return"Arcane Missiles! (4 charges)"end if charges>=4 then if UnitExists("target")then local hasNT,ntR=CTD(SPELL_NETHER_TEMPEST)if hasNT and ntR>0 and ntR<4 then return"Odswiez Nether Tempest!"end end return"Arcane Barrage (4 charges)!"end if UnitExists("target")then local hasNT,ntR=CTD(SPELL_NETHER_TEMPEST)if not hasNT and d>2 then return"Naloz Nether Tempest!"end end if utils.IsSpellReady(SPELL_ARCANE_POWER)and d>10 then return"Arcane Power gotowe!"end return""end
function module.GetAdviceSpellIcon(a,f)if not f then return nil end local n=GetTime()local d=n-f.startTime local hasAM,_=CPB(SPELL_ARCANE_MISSILES_BUFF)local charges=GAC()if hasAM and charges>=4 then return SPELL_ARCANE_MISSILES end if charges>=4 then return SPELL_ARCANE_BARRAGE end if UnitExists("target")then local hasNT,ntR=CTD(SPELL_NETHER_TEMPEST)if not hasNT and d>2 then return SPELL_NETHER_TEMPEST end if hasNT and ntR>0 and ntR<4 then return SPELL_NETHER_TEMPEST end end if utils.IsSpellReady(SPELL_ARCANE_POWER)and d>10 then return SPELL_ARCANE_POWER end return nil end
local APL_PRIORITY={{id="ap",spellId=SPELL_ARCANE_POWER,name="Arcane Power",condition=function(s)return s.apReady and s.duration>10 end,priority=1,category="cooldown"},{id="am_4",spellId=SPELL_ARCANE_MISSILES,name="AM(4ch)",condition=function(s)return s.amProc and s.charges>=4 end,priority=2,category="proc"},{id="nt_m",spellId=SPELL_NETHER_TEMPEST,name="Nether Tempest",condition=function(s)return s.ntMissing and s.duration>2 end,priority=3,category="dot"},{id="ab_4",spellId=SPELL_ARCANE_BARRAGE,name="Barrage(4ch)",condition=function(s)return s.charges>=4 end,priority=4,category="dump"},{id="nt_r",spellId=SPELL_NETHER_TEMPEST,name="NT(refresh)",condition=function(s)return s.ntExpiring end,priority=5,category="dot"},{id="abl",spellId=SPELL_ARCANE_BLAST,name="Arcane Blast",condition=function(s)return true end,priority=6,category="builder"}}
local function GCS(a,f)local s={duration=0,amProc=false,charges=0,apReady=false,ntMissing=false,ntExpiring=false}if not f then return s end local n=GetTime()s.duration=n-(f.startTime or n)s.amProc=CPB(SPELL_ARCANE_MISSILES_BUFF)s.charges=GAC()s.apReady=utils.IsSpellReady(SPELL_ARCANE_POWER)if UnitExists("target")and s.duration>2 then local hasNT,ntR=CTD(SPELL_NETHER_TEMPEST)s.ntMissing=not hasNT s.ntExpiring=hasNT and ntR>0 and ntR<4 end return s end
function module.GetNextAPLAction(a,f)local s=GCS(a,f)for _,act in ipairs(APL_PRIORITY)do if act.condition(s)then return act end end return APL_PRIORITY[#APL_PRIORITY]end
function module.GetAPLPriorityList()return APL_PRIORITY end
function module.GetRotationState(a,f)return GCS(a,f)end
function module.EvaluateCast(a,f,sid,ts)local nA=module.GetNextAPLAction(a,f)if not nA then return nil end local isO=(nA.spellId==sid)local pen=0 local rsn=""if not isO then local cP=nil for _,act in ipairs(APL_PRIORITY)do if act.spellId==sid then cP=act.priority break end end if cP then pen=math.abs(nA.priority-cP)*2 rsn=string.format("Powinienes: %s",nA.name)else pen=5 rsn="Spell poza APL"end end return{isOptimal=isO,penalty=pen,reason=rsn,expectedSpell=nA.spellId,expectedName=nA.name,actualSpell=sid}end
function module.RecordCastEvaluation(f,ev,ts)if not f.rotation then return end f.rotation.totalCasts=f.rotation.totalCasts+1 if ev.isOptimal then f.rotation.optimalCasts=f.rotation.optimalCasts+1 else f.rotation.suboptimalCasts=f.rotation.suboptimalCasts+1 f.rotation.penaltySum=f.rotation.penaltySum+ev.penalty table.insert(f.rotation.mistakes,{timestamp=ts,reason=ev.reason,penalty=ev.penalty,expected=ev.expectedName})end end
function module.GetRotationScore(f)if not f.rotation or f.rotation.totalCasts==0 then return nil end return{accuracy=f.rotation.optimalCasts/f.rotation.totalCasts,totalCasts=f.rotation.totalCasts,optimalCasts=f.rotation.optimalCasts,suboptimalCasts=f.rotation.suboptimalCasts,mistakes=f.rotation.mistakes,penaltySum=f.rotation.penaltySum}end
Analyzer:RegisterClassModule(module.class,module)
