local _,Analyzer=...if not Analyzer then return end
local module={}
local utils=Analyzer.utils
module.name="Mage - Fire"
module.class="MAGE"
module.specKey="fire"
module.specIndex=2
module.specId=63
local SPELL_FIREBALL=133
local SPELL_PYROBLAST=11366
local SPELL_INFERNO_BLAST=108853
local SPELL_COMBUSTION=11129
local SPELL_LIVING_BOMB=44457
local SPELL_SCORCH=2948
local SPELL_FLAMESTRIKE=2120
local SPELL_ALTER_TIME=108978
local SPELL_HEATING_UP=48107
local SPELL_PYROBLAST_BUFF=48108
local SPELL_COMBUSTION_DOT=83853
local SPELL_IGNITE=12654
local COOLDOWN_COMBUSTION=45
local COOLDOWN_ALTER_TIME=180
local SOUND_KEY_HEATING_UP="heatingUp"
local SOUND_KEY_PYROBLAST="pyroblast"
local TRACKED_BUFFS={[SPELL_HEATING_UP]=true,[SPELL_PYROBLAST_BUFF]=true,[SPELL_ALTER_TIME]=true}
local TRACKED_DEBUFFS={[SPELL_LIVING_BOMB]=true,[SPELL_COMBUSTION_DOT]=true,[SPELL_IGNITE]=true}
local TRACKED_CASTS={[SPELL_FIREBALL]=true,[SPELL_PYROBLAST]=true,[SPELL_INFERNO_BLAST]=true,[SPELL_COMBUSTION]=true,[SPELL_LIVING_BOMB]=true,[SPELL_SCORCH]=true}
local function EH(c,s)c[s]=c[s]or{}return c[s]end
function module.SupportsSpec(a)if a.player.class~=module.class then return false end if a.player.specId==module.specId then return true end local sk=utils.NormalizeSpecKey(a.player.specName)if sk==module.specKey then return true end if a.player.specIndex==module.specIndex then return true end return false end
function module.OnPlayerInit(a)if a.player.class~=module.class then return end if a.player.specName~="Unknown"then return end if IsSpellKnown and IsSpellKnown(SPELL_PYROBLAST)then a.player.specName="Fire"a.player.specId=a.player.specId or module.specId a.player.specIndex=a.player.specIndex or module.specIndex end end
function module.GetDefaultSettings()return{sounds={[SOUND_KEY_HEATING_UP]={enabled=true,sound="Sound\\Interface\\RaidWarning.ogg"},[SOUND_KEY_PYROBLAST]={enabled=true,sound="Sound\\Interface\\MapPing.ogg"}}}end
function module.GetSoundOptions()return{{key=SOUND_KEY_HEATING_UP,label="Heating Up"},{key=SOUND_KEY_PYROBLAST,label="Pyroblast!"}}end
function module.IsTrackedBuffSpell(s)return TRACKED_BUFFS[s]==true end
function module.IsTrackedDebuffSpell(s)return TRACKED_DEBUFFS[s]==true end
function module.IsTrackedCast(s)return TRACKED_CASTS[s]==true end
function module.ShouldRecordCast(e)if not e or not e.spellId then return false end return TRACKED_CASTS[e.spellId]==true end
function module.GetProcInfo(s)if s==SPELL_HEATING_UP then return{soundKey=SOUND_KEY_HEATING_UP,priority=2}elseif s==SPELL_PYROBLAST_BUFF then return{soundKey=SOUND_KEY_PYROBLAST,priority=3}end return nil end
function module.InitFight(_,f)f.procs={heatingUpProcs=0,pyroblastProcs=0,pyroblastConsumed=0}f.cooldowns={combustionLast=0,alterTimeLast=0}f.castLog={}f.buffHistory={}f.debuffHistory={}f.rotation={totalCasts=0,optimalCasts=0,suboptimalCasts=0,mistakes={},penaltySum=0}end
function module.TrackSpellCast(a,s,t)local f=a.fight if not f or not TRACKED_CASTS[s]then return end local n=utils.NormalizeTimestamp(t)f.spells[s]=(f.spells[s]or 0)+1 table.insert(f.castLog,{spellId=s,timestamp=n})if s==SPELL_PYROBLAST then local b=f.buffs[SPELL_PYROBLAST_BUFF]if b and(b.stacks or 0)>0 then f.procs.pyroblastConsumed=f.procs.pyroblastConsumed+1 b.consumed=true b.stacks=0 end elseif s==SPELL_COMBUSTION then f.cooldowns.combustionLast=n a:AddTimelineEvent(s,n,"cooldown")a:AddEventLog(n,"Combustion",s)elseif s==SPELL_INFERNO_BLAST then a:AddEventLog(n,"Inferno Blast",s)end local cS={[SPELL_FIREBALL]=true,[SPELL_PYROBLAST]=true,[SPELL_INFERNO_BLAST]=true,[SPELL_LIVING_BOMB]=true}if cS[s]and f.rotation then local ev=module.EvaluateCast(a,f,s,n)if ev then module.RecordCastEvaluation(f,ev,n)end end end
function module.TrackAura(a,se,s,am,t)local f=a.fight if not f then return end local n=utils.NormalizeTimestamp(t)if se=="SPELL_AURA_APPLIED"or se=="SPELL_AURA_APPLIED_DOSE"or se=="SPELL_AURA_REFRESH"then local st=am or 1 local b=f.buffs[s]local isR=(se=="SPELL_AURA_REFRESH")if b and isR and b.since then f.buffUptime[s]=(f.buffUptime[s]or 0)+(n-b.since)end if not b then b={stacks=st,since=n}f.buffs[s]=b else b.stacks=st b.since=b.since or n end if isR then b.since=n end local h=EH(f.buffHistory,s)if isR and b.historyEntry and not b.historyEntry.removed then b.historyEntry.removed=n end if not b.historyEntry or isR then b.historyEntry={applied=n}table.insert(h,b.historyEntry)end if s==SPELL_HEATING_UP then if not isR then f.procs.heatingUpProcs=f.procs.heatingUpProcs+1 end a:PlayAlertSound(SOUND_KEY_HEATING_UP,n)elseif s==SPELL_PYROBLAST_BUFF then if not isR then f.procs.pyroblastProcs=f.procs.pyroblastProcs+1 a:AddTimelineEvent(s,n,"proc")a:AddEventLog(n,"Pyroblast! proc",s)end a:PlayAlertSound(SOUND_KEY_PYROBLAST,n)end elseif se=="SPELL_AURA_REMOVED"then local b=f.buffs[s]if b then if b.since then f.buffUptime[s]=(f.buffUptime[s]or 0)+(n-b.since)end if b.historyEntry and not b.historyEntry.removed then b.historyEntry.removed=n end end f.buffs[s]=nil end end
function module.TrackDebuff(a,se,s,dG,dN,t)local f=a.fight if not f or not TRACKED_DEBUFFS[s]then return end local n=utils.NormalizeTimestamp(t)if not f.primaryTargetGUID then f.primaryTargetGUID=dG end if dG and f.primaryTargetGUID and dG~=f.primaryTargetGUID then return end if dG then f.targets[dG]=true end local d=f.debuffs[s]local h=EH(f.debuffHistory,s)if se=="SPELL_AURA_APPLIED"then f.debuffs[s]={since=n,targetGUID=dG}local e={applied=n}table.insert(h,e)f.debuffs[s].historyEntry=e elseif se=="SPELL_AURA_REFRESH"then if d and d.since then f.debuffUptime[s]=(f.debuffUptime[s]or 0)+(n-d.since)end if d and d.historyEntry and not d.historyEntry.removed then d.historyEntry.removed=n end f.debuffs[s]={since=n,targetGUID=dG}local e={applied=n}table.insert(h,e)f.debuffs[s].historyEntry=e elseif se=="SPELL_AURA_REMOVED"then if d and d.since then f.debuffUptime[s]=(f.debuffUptime[s]or 0)+(n-d.since)end if d and d.historyEntry and not d.historyEntry.removed then d.historyEntry.removed=n end f.debuffs[s]=nil end end
function module.Analyze(a,f,c)local m={}local i={}local sc=100 if c.duration<15 then utils.AddIssue(i,"Walka zbyt krotka.")return{score=0,metrics=m,issues=i}end local function AM(l,s,v,p,st,it,pen)table.insert(m,{label=l,spellId=s,valueText=v or"",percent=p,status=st or"info"})utils.AddIssue(i,it)if pen and pen>0 then sc=utils.Clamp(sc-pen,0,100)end end local lbUp=utils.SafePercent(f.debuffUptime[SPELL_LIVING_BOMB]or 0,c.duration)local lbSt=utils.StatusForPercent(lbUp,0.95,0.85)AM("Living Bomb uptime",SPELL_LIVING_BOMB,utils.FormatPercent(lbUp),lbUp,lbSt,lbSt=="bad"and"Niski uptime Living Bomb."or(lbSt=="warn"and"Living Bomb moglby byc wyzszy."or nil),lbSt=="bad"and 12 or(lbSt=="warn"and 6 or 0))local pyroP=f.procs.pyroblastProcs or 0 local pyroC=f.procs.pyroblastConsumed or 0 if pyroP>0 then local pyroU=utils.SafePercent(pyroC,pyroP)local pyroSt=utils.StatusForPercent(pyroU,0.90,0.75)AM("Pyroblast! wykorzystanie",SPELL_PYROBLAST_BUFF,string.format("%s (%d/%d)",utils.FormatPercent(pyroU),pyroC,pyroP),pyroU,pyroSt,pyroSt=="bad"and"Za duzo Pyroblast! nie zuzyte."or(pyroSt=="warn"and"Czesc Pyroblast! sie marnuje."or nil),pyroSt=="bad"and 15 or(pyroSt=="warn"and 8 or 0))end local comb=f.spells[SPELL_COMBUSTION]or 0 local expC=utils.ExpectedUses(c.duration,COOLDOWN_COMBUSTION,10)if expC>0 then local cP=utils.SafePercent(comb,expC)local cSt=utils.StatusForPercent(cP,0.80,0.60)AM("Combustion uzycia",SPELL_COMBUSTION,string.format("%d/%d",comb,expC),math.min(cP or 0,1),cSt,cSt=="bad"and"Za malo Combustion."or(cSt=="warn"and"Combustion uzywany zbyt rzadko."or nil),cSt=="bad"and 10 or(cSt=="warn"and 5 or 0))end if f.rotation and f.rotation.totalCasts>0 then local rS=module.GetRotationScore(f)if rS then local rA=rS.accuracy or 0 local rSt=utils.StatusForPercent(rA,0.85,0.70)AM("Dokladnosc rotacji (APL)",nil,string.format("%.0f%% (%d/%d)",rA*100,rS.optimalCasts,rS.totalCasts),rA,rSt,rSt=="bad"and"Niska dokladnosc."or(rSt=="warn"and"Srednia dokladnosc."or nil),rSt=="bad"and 10 or(rSt=="warn"and 5 or 0))if rS.mistakes and #rS.mistakes>0 then local mC={}for _,mk in ipairs(rS.mistakes)do mC[mk.reason or"Unknown"]=(mC[mk.reason or"Unknown"]or 0)+1 end local sM={}for r,ct in pairs(mC)do table.insert(sM,{reason=r,count=ct})end table.sort(sM,function(x,y)return x.count>y.count end)for j=1,math.min(3,#sM)do local mk=sM[j]if mk.count>=2 then utils.AddIssue(i,string.format("Blad rotacji (%dx): %s",mk.count,mk.reason))end end end end end sc=utils.Clamp(sc,0,100)return{score=sc,metrics=m,issues=i}end
function module.GetLiveScore(a,f)if not f then return nil end local n=GetTime()local d=n-f.startTime if d<5 then return nil end return 100 end
local function CPB(s)if not s then return false end for i=1,40 do local _,_,_,_,_,_,_,_,_,aS=UnitBuff("player",i)if not aS then break end if aS==s then return true end end return false end
local function CTD(s)if not s or not UnitExists("target")then return false,0 end for i=1,40 do local _,_,_,_,_,eT,_,c,_,_,aS=UnitDebuff("target",i)if not aS then break end if aS==s and c=="player"then local r=eT and(eT-GetTime())or 0 return true,r end end return false,0 end
function module.GetLiveAdvice(a,f)if not f then return""end local n=GetTime()local d=n-f.startTime local hasPyro=CPB(SPELL_PYROBLAST_BUFF)if hasPyro then return"Pyroblast! Uzyj teraz!"end local hasHU=CPB(SPELL_HEATING_UP)if hasHU and utils.IsSpellReady(SPELL_INFERNO_BLAST)then return"Heating Up! Inferno Blast!"end if UnitExists("target")then local hasLB,lbR=CTD(SPELL_LIVING_BOMB)if not hasLB and d>2 then return"Naloz Living Bomb!"end if hasLB and lbR>0 and lbR<3 then return"Living Bomb wygasa!"end end if utils.IsSpellReady(SPELL_COMBUSTION)and d>10 then return"Combustion gotowe!"end return""end
function module.GetAdviceSpellIcon(a,f)if not f then return nil end local n=GetTime()local d=n-f.startTime local hasPyro=CPB(SPELL_PYROBLAST_BUFF)if hasPyro then return SPELL_PYROBLAST end local hasHU=CPB(SPELL_HEATING_UP)if hasHU and utils.IsSpellReady(SPELL_INFERNO_BLAST)then return SPELL_INFERNO_BLAST end if UnitExists("target")then local hasLB,lbR=CTD(SPELL_LIVING_BOMB)if not hasLB and d>2 then return SPELL_LIVING_BOMB end if hasLB and lbR>0 and lbR<3 then return SPELL_LIVING_BOMB end end if utils.IsSpellReady(SPELL_COMBUSTION)and d>10 then return SPELL_COMBUSTION end return nil end
local APL_PRIORITY={{id="pyro_proc",spellId=SPELL_PYROBLAST,name="Pyroblast!",condition=function(s)return s.pyroblastProc end,priority=1,category="proc"},{id="ib_hu",spellId=SPELL_INFERNO_BLAST,name="Inferno Blast(HU)",condition=function(s)return s.heatingUp and s.ibReady end,priority=2,category="proc"},{id="lb_m",spellId=SPELL_LIVING_BOMB,name="Living Bomb",condition=function(s)return s.lbMissing and s.duration>2 end,priority=3,category="dot"},{id="comb",spellId=SPELL_COMBUSTION,name="Combustion",condition=function(s)return s.combReady and s.duration>10 end,priority=4,category="cooldown"},{id="lb_r",spellId=SPELL_LIVING_BOMB,name="Living Bomb(r)",condition=function(s)return s.lbExpiring end,priority=5,category="dot"},{id="fb",spellId=SPELL_FIREBALL,name="Fireball",condition=function(s)return true end,priority=6,category="filler"}}
local function GCS(a,f)local s={duration=0,pyroblastProc=false,heatingUp=false,ibReady=false,combReady=false,lbMissing=false,lbExpiring=false}if not f then return s end local n=GetTime()s.duration=n-(f.startTime or n)s.pyroblastProc=CPB(SPELL_PYROBLAST_BUFF)s.heatingUp=CPB(SPELL_HEATING_UP)s.ibReady=utils.IsSpellReady(SPELL_INFERNO_BLAST)s.combReady=utils.IsSpellReady(SPELL_COMBUSTION)if UnitExists("target")and s.duration>2 then local hasLB,lbR=CTD(SPELL_LIVING_BOMB)s.lbMissing=not hasLB s.lbExpiring=hasLB and lbR>0 and lbR<3 end return s end
function module.GetNextAPLAction(a,f)local s=GCS(a,f)for _,act in ipairs(APL_PRIORITY)do if act.condition(s)then return act end end return APL_PRIORITY[#APL_PRIORITY]end
function module.GetAPLPriorityList()return APL_PRIORITY end
function module.GetRotationState(a,f)return GCS(a,f)end
function module.EvaluateCast(a,f,sid,ts)local nA=module.GetNextAPLAction(a,f)if not nA then return nil end local isO=(nA.spellId==sid)local pen=0 local rsn=""if not isO then local cP=nil for _,act in ipairs(APL_PRIORITY)do if act.spellId==sid then cP=act.priority break end end if cP then pen=math.abs(nA.priority-cP)*2 rsn=string.format("Powinienes: %s",nA.name)else pen=5 rsn="Spell poza APL"end end return{isOptimal=isO,penalty=pen,reason=rsn,expectedSpell=nA.spellId,expectedName=nA.name,actualSpell=sid}end
function module.RecordCastEvaluation(f,ev,ts)if not f.rotation then return end f.rotation.totalCasts=f.rotation.totalCasts+1 if ev.isOptimal then f.rotation.optimalCasts=f.rotation.optimalCasts+1 else f.rotation.suboptimalCasts=f.rotation.suboptimalCasts+1 f.rotation.penaltySum=f.rotation.penaltySum+ev.penalty table.insert(f.rotation.mistakes,{timestamp=ts,reason=ev.reason,penalty=ev.penalty,expected=ev.expectedName})end end
function module.GetRotationScore(f)if not f.rotation or f.rotation.totalCasts==0 then return nil end return{accuracy=f.rotation.optimalCasts/f.rotation.totalCasts,totalCasts=f.rotation.totalCasts,optimalCasts=f.rotation.optimalCasts,suboptimalCasts=f.rotation.suboptimalCasts,mistakes=f.rotation.mistakes,penaltySum=f.rotation.penaltySum}end
Analyzer:RegisterClassModule(module.class,module)
