local _,Analyzer=...if not Analyzer then return end
local module={}
local utils=Analyzer.utils
module.name="Rogue - Subtlety"
module.class="ROGUE"
module.specKey="subtlety"
module.specIndex=3
module.specId=261
local SPELL_BACKSTAB=53
local SPELL_AMBUSH=8676
local SPELL_EVISCERATE=2098
local SPELL_RUPTURE=1943
local SPELL_SLICE_AND_DICE=5171
local SPELL_HEMORRHAGE=16511
local SPELL_SHADOW_DANCE=51713
local SPELL_VANISH=1856
local SPELL_PREPARATION=14185
local SPELL_FIND_WEAKNESS=91023
local SPELL_SHADOW_BLADES=121471
local COOLDOWN_SHADOW_DANCE=60
local COOLDOWN_VANISH=180
local SOUND_KEY_SHADOW_DANCE="shadowDance"
local SOUND_KEY_FIND_WEAKNESS="findWeakness"
local TRACKED_BUFFS={[SPELL_SLICE_AND_DICE]=true,[SPELL_SHADOW_DANCE]=true,[SPELL_SHADOW_BLADES]=true}
local TRACKED_DEBUFFS={[SPELL_RUPTURE]=true,[SPELL_HEMORRHAGE]=true,[SPELL_FIND_WEAKNESS]=true}
local TRACKED_CASTS={[SPELL_BACKSTAB]=true,[SPELL_AMBUSH]=true,[SPELL_EVISCERATE]=true,[SPELL_RUPTURE]=true,[SPELL_SLICE_AND_DICE]=true,[SPELL_HEMORRHAGE]=true,[SPELL_SHADOW_DANCE]=true}
local function EH(c,s)c[s]=c[s]or{}return c[s]end
function module.SupportsSpec(a)if a.player.class~=module.class then return false end if a.player.specId==module.specId then return true end local sk=utils.NormalizeSpecKey(a.player.specName)if sk==module.specKey then return true end if a.player.specIndex==module.specIndex then return true end return false end
function module.OnPlayerInit(a)if a.player.class~=module.class then return end if a.player.specName~="Unknown"then return end if IsSpellKnown and IsSpellKnown(SPELL_SHADOW_DANCE)then a.player.specName="Subtlety"a.player.specId=a.player.specId or module.specId a.player.specIndex=a.player.specIndex or module.specIndex end end
function module.GetDefaultSettings()return{sounds={[SOUND_KEY_SHADOW_DANCE]={enabled=true,sound="Sound\\Interface\\RaidWarning.ogg"},[SOUND_KEY_FIND_WEAKNESS]={enabled=true,sound="Sound\\Interface\\MapPing.ogg"}}}end
function module.GetSoundOptions()return{{key=SOUND_KEY_SHADOW_DANCE,label="Shadow Dance"},{key=SOUND_KEY_FIND_WEAKNESS,label="Find Weakness"}}end
function module.IsTrackedBuffSpell(s)return TRACKED_BUFFS[s]==true end
function module.IsTrackedDebuffSpell(s)return TRACKED_DEBUFFS[s]==true end
function module.IsTrackedCast(s)return TRACKED_CASTS[s]==true end
function module.ShouldRecordCast(e)if not e or not e.spellId then return false end return TRACKED_CASTS[e.spellId]==true end
function module.GetProcInfo(s)if s==SPELL_SHADOW_DANCE then return{soundKey=SOUND_KEY_SHADOW_DANCE,priority=3}elseif s==SPELL_FIND_WEAKNESS then return{soundKey=SOUND_KEY_FIND_WEAKNESS,priority=2}end return nil end
function module.InitFight(_,f)f.procs={findWeaknessApplied=0}f.cooldowns={shadowDanceLast=0,vanishLast=0}f.castLog={}f.buffHistory={}f.debuffHistory={}f.rotation={totalCasts=0,optimalCasts=0,suboptimalCasts=0,mistakes={},penaltySum=0}end
function module.TrackSpellCast(a,s,t)local f=a.fight if not f or not TRACKED_CASTS[s]then return end local n=utils.NormalizeTimestamp(t)f.spells[s]=(f.spells[s]or 0)+1 table.insert(f.castLog,{spellId=s,timestamp=n})if s==SPELL_SHADOW_DANCE then f.cooldowns.shadowDanceLast=n a:AddTimelineEvent(s,n,"cooldown")a:AddEventLog(n,"Shadow Dance",s)elseif s==SPELL_AMBUSH then a:AddEventLog(n,"Ambush",s)end local cS={[SPELL_BACKSTAB]=true,[SPELL_AMBUSH]=true,[SPELL_EVISCERATE]=true,[SPELL_RUPTURE]=true,[SPELL_HEMORRHAGE]=true}if cS[s]and f.rotation then local ev=module.EvaluateCast(a,f,s,n)if ev then module.RecordCastEvaluation(f,ev,n)end end end
function module.TrackAura(a,se,s,am,t)local f=a.fight if not f then return end local n=utils.NormalizeTimestamp(t)if se=="SPELL_AURA_APPLIED"or se=="SPELL_AURA_APPLIED_DOSE"or se=="SPELL_AURA_REFRESH"then local st=am or 1 local b=f.buffs[s]local isR=(se=="SPELL_AURA_REFRESH")if b and isR and b.since then f.buffUptime[s]=(f.buffUptime[s]or 0)+(n-b.since)end if not b then b={stacks=st,since=n}f.buffs[s]=b else b.stacks=st b.since=b.since or n end if isR then b.since=n end local h=EH(f.buffHistory,s)if isR and b.historyEntry and not b.historyEntry.removed then b.historyEntry.removed=n end if not b.historyEntry or isR then b.historyEntry={applied=n}table.insert(h,b.historyEntry)end if s==SPELL_SHADOW_DANCE then a:PlayAlertSound(SOUND_KEY_SHADOW_DANCE,n)end elseif se=="SPELL_AURA_REMOVED"then local b=f.buffs[s]if b then if b.since then f.buffUptime[s]=(f.buffUptime[s]or 0)+(n-b.since)end if b.historyEntry and not b.historyEntry.removed then b.historyEntry.removed=n end end f.buffs[s]=nil end end
function module.TrackDebuff(a,se,s,dG,dN,t)local f=a.fight if not f or not TRACKED_DEBUFFS[s]then return end local n=utils.NormalizeTimestamp(t)if not f.primaryTargetGUID then f.primaryTargetGUID=dG end if dG and f.primaryTargetGUID and dG~=f.primaryTargetGUID then return end if dG then f.targets[dG]=true end local d=f.debuffs[s]local h=EH(f.debuffHistory,s)if se=="SPELL_AURA_APPLIED"then f.debuffs[s]={since=n,targetGUID=dG}local e={applied=n}table.insert(h,e)f.debuffs[s].historyEntry=e if s==SPELL_FIND_WEAKNESS then f.procs.findWeaknessApplied=f.procs.findWeaknessApplied+1 a:PlayAlertSound(SOUND_KEY_FIND_WEAKNESS,n)end elseif se=="SPELL_AURA_REFRESH"then if d and d.since then f.debuffUptime[s]=(f.debuffUptime[s]or 0)+(n-d.since)end if d and d.historyEntry and not d.historyEntry.removed then d.historyEntry.removed=n end f.debuffs[s]={since=n,targetGUID=dG}local e={applied=n}table.insert(h,e)f.debuffs[s].historyEntry=e elseif se=="SPELL_AURA_REMOVED"then if d and d.since then f.debuffUptime[s]=(f.debuffUptime[s]or 0)+(n-d.since)end if d and d.historyEntry and not d.historyEntry.removed then d.historyEntry.removed=n end f.debuffs[s]=nil end end
function module.Analyze(a,f,c)local m={}local i={}local sc=100 if c.duration<15 then utils.AddIssue(i,"Walka zbyt krotka.")return{score=0,metrics=m,issues=i}end local function AM(l,s,v,p,st,it,pen)table.insert(m,{label=l,spellId=s,valueText=v or"",percent=p,status=st or"info"})utils.AddIssue(i,it)if pen and pen>0 then sc=utils.Clamp(sc-pen,0,100)end end local rupUp=utils.SafePercent(f.debuffUptime[SPELL_RUPTURE]or 0,c.duration)local rupSt=utils.StatusForPercent(rupUp,0.95,0.85)AM("Rupture uptime",SPELL_RUPTURE,utils.FormatPercent(rupUp),rupUp,rupSt,rupSt=="bad"and"Niski uptime Rupture."or(rupSt=="warn"and"Rupture moglby byc wyzszy."or nil),rupSt=="bad"and 15 or(rupSt=="warn"and 8 or 0))local sndUp=utils.SafePercent(f.buffUptime[SPELL_SLICE_AND_DICE]or 0,c.duration)local sndSt=utils.StatusForPercent(sndUp,0.95,0.85)AM("Slice and Dice uptime",SPELL_SLICE_AND_DICE,utils.FormatPercent(sndUp),sndUp,sndSt,sndSt=="bad"and"Niski uptime SnD."or(sndSt=="warn"and"SnD moglby byc wyzszy."or nil),sndSt=="bad"and 15 or(sndSt=="warn"and 8 or 0))local fwUp=utils.SafePercent(f.debuffUptime[SPELL_FIND_WEAKNESS]or 0,c.duration)AM("Find Weakness uptime",SPELL_FIND_WEAKNESS,utils.FormatPercent(fwUp),fwUp,"info",nil,0)local sd=f.spells[SPELL_SHADOW_DANCE]or 0 local expSD=utils.ExpectedUses(c.duration,COOLDOWN_SHADOW_DANCE,10)if expSD>0 then local sdP=utils.SafePercent(sd,expSD)local sdSt=utils.StatusForPercent(sdP,1.0,0.7)AM("Shadow Dance uzycia",SPELL_SHADOW_DANCE,string.format("%d/%d",sd,expSD),math.min(sdP or 0,1),sdSt,sd<expSD and"Za malo Shadow Dance."or nil,sd<expSD and 10 or 0)end if f.rotation and f.rotation.totalCasts>0 then local rS=module.GetRotationScore(f)if rS then local rA=rS.accuracy or 0 local rSt=utils.StatusForPercent(rA,0.85,0.70)AM("Dokladnosc rotacji (APL)",nil,string.format("%.0f%% (%d/%d)",rA*100,rS.optimalCasts,rS.totalCasts),rA,rSt,rSt=="bad"and"Niska dokladnosc."or(rSt=="warn"and"Srednia dokladnosc."or nil),rSt=="bad"and 10 or(rSt=="warn"and 5 or 0))if rS.mistakes and #rS.mistakes>0 then local mC={}for _,mk in ipairs(rS.mistakes)do mC[mk.reason or"Unknown"]=(mC[mk.reason or"Unknown"]or 0)+1 end local sM={}for r,ct in pairs(mC)do table.insert(sM,{reason=r,count=ct})end table.sort(sM,function(x,y)return x.count>y.count end)for j=1,math.min(3,#sM)do local mk=sM[j]if mk.count>=2 then utils.AddIssue(i,string.format("Blad rotacji (%dx): %s",mk.count,mk.reason))end end end end end sc=utils.Clamp(sc,0,100)return{score=sc,metrics=m,issues=i}end
function module.GetLiveScore(a,f)if not f then return nil end local n=GetTime()local d=n-f.startTime if d<5 then return nil end return 100 end
local function CPB(s)if not s then return false end for i=1,40 do local _,_,_,_,_,_,_,_,_,aS=UnitBuff("player",i)if not aS then break end if aS==s then return true end end return false end
local function CTD(s)if not s or not UnitExists("target")then return false,0 end for i=1,40 do local _,_,_,_,_,eT,_,c,_,_,aS=UnitDebuff("target",i)if not aS then break end if aS==s and c=="player"then local r=eT and(eT-GetTime())or 0 return true,r end end return false,0 end
local function GetCP()if UnitPower then return UnitPower("player",4)end return 0 end
function module.GetLiveAdvice(a,f)if not f then return""end local n=GetTime()local d=n-f.startTime local inSD=CPB(SPELL_SHADOW_DANCE)if inSD then return"Shadow Dance! Ambush spam!"end local cp=GetCP()if cp>=5 then local hasRup,rupR=CTD(SPELL_RUPTURE)if not hasRup or(hasRup and rupR>0 and rupR<5)then return"5 CP! Rupture!"end if not CPB(SPELL_SLICE_AND_DICE)then return"5 CP! Slice and Dice!"end return"5 CP! Eviscerate!"end if utils.IsSpellReady(SPELL_SHADOW_DANCE)and d>10 then return"Shadow Dance gotowe!"end return""end
function module.GetAdviceSpellIcon(a,f)if not f then return nil end local n=GetTime()local d=n-f.startTime local inSD=CPB(SPELL_SHADOW_DANCE)if inSD then return SPELL_AMBUSH end local cp=GetCP()if cp>=5 then local hasRup,rupR=CTD(SPELL_RUPTURE)if not hasRup or(hasRup and rupR>0 and rupR<5)then return SPELL_RUPTURE end if not CPB(SPELL_SLICE_AND_DICE)then return SPELL_SLICE_AND_DICE end return SPELL_EVISCERATE end if utils.IsSpellReady(SPELL_SHADOW_DANCE)and d>10 then return SPELL_SHADOW_DANCE end return nil end
local APL_PRIORITY={{id="amb_sd",spellId=SPELL_AMBUSH,name="Ambush(SD)",condition=function(s)return s.inShadowDance end,priority=1,category="burst"},{id="rup_m",spellId=SPELL_RUPTURE,name="Rupture",condition=function(s)return s.cp>=5 and s.rupMissing end,priority=2,category="finisher"},{id="snd_m",spellId=SPELL_SLICE_AND_DICE,name="SnD",condition=function(s)return s.cp>=1 and s.sndMissing and s.duration>3 end,priority=3,category="finisher"},{id="evis",spellId=SPELL_EVISCERATE,name="Eviscerate",condition=function(s)return s.cp>=5 end,priority=4,category="finisher"},{id="rup_r",spellId=SPELL_RUPTURE,name="Rupture(r)",condition=function(s)return s.cp>=4 and s.rupExpiring end,priority=5,category="finisher"},{id="hemo",spellId=SPELL_HEMORRHAGE,name="Hemorrhage",condition=function(s)return s.hemoMissing end,priority=6,category="debuff"},{id="bs",spellId=SPELL_BACKSTAB,name="Backstab",condition=function(s)return true end,priority=7,category="builder"}}
local function GCS(a,f)local s={duration=0,cp=0,inShadowDance=false,rupMissing=false,rupExpiring=false,sndMissing=false,hemoMissing=false}if not f then return s end local n=GetTime()s.duration=n-(f.startTime or n)s.cp=GetCP()s.inShadowDance=CPB(SPELL_SHADOW_DANCE)s.sndMissing=not CPB(SPELL_SLICE_AND_DICE)if UnitExists("target")and s.duration>2 then local hasRup,rupR=CTD(SPELL_RUPTURE)local hasHemo=CTD(SPELL_HEMORRHAGE)s.rupMissing=not hasRup s.rupExpiring=hasRup and rupR>0 and rupR<5 s.hemoMissing=not hasHemo end return s end
function module.GetNextAPLAction(a,f)local s=GCS(a,f)for _,act in ipairs(APL_PRIORITY)do if act.condition(s)then return act end end return APL_PRIORITY[#APL_PRIORITY]end
function module.GetAPLPriorityList()return APL_PRIORITY end
function module.GetRotationState(a,f)return GCS(a,f)end
function module.EvaluateCast(a,f,sid,ts)local nA=module.GetNextAPLAction(a,f)if not nA then return nil end local isO=(nA.spellId==sid)local pen=0 local rsn=""if not isO then local cP=nil for _,act in ipairs(APL_PRIORITY)do if act.spellId==sid then cP=act.priority break end end if cP then pen=math.abs(nA.priority-cP)*2 rsn=string.format("Powinienes: %s",nA.name)else pen=5 rsn="Spell poza APL"end end return{isOptimal=isO,penalty=pen,reason=rsn,expectedSpell=nA.spellId,expectedName=nA.name,actualSpell=sid}end
function module.RecordCastEvaluation(f,ev,ts)if not f.rotation then return end f.rotation.totalCasts=f.rotation.totalCasts+1 if ev.isOptimal then f.rotation.optimalCasts=f.rotation.optimalCasts+1 else f.rotation.suboptimalCasts=f.rotation.suboptimalCasts+1 f.rotation.penaltySum=f.rotation.penaltySum+ev.penalty table.insert(f.rotation.mistakes,{timestamp=ts,reason=ev.reason,penalty=ev.penalty,expected=ev.expectedName})end end
function module.GetRotationScore(f)if not f.rotation or f.rotation.totalCasts==0 then return nil end return{accuracy=f.rotation.optimalCasts/f.rotation.totalCasts,totalCasts=f.rotation.totalCasts,optimalCasts=f.rotation.optimalCasts,suboptimalCasts=f.rotation.suboptimalCasts,mistakes=f.rotation.mistakes,penaltySum=f.rotation.penaltySum}end
Analyzer:RegisterClassModule(module.class,module)
