local _,Analyzer=...if not Analyzer then return end
local module={}
local utils=Analyzer.utils
module.name="Shaman - Enhancement"
module.class="SHAMAN"
module.specKey="enhancement"
module.specIndex=2
module.specId=263
local SPELL_STORMSTRIKE=17364
local SPELL_LAVA_LASH=60103
local SPELL_FLAME_SHOCK=8050
local SPELL_EARTH_SHOCK=8042
local SPELL_LIGHTNING_BOLT=403
local SPELL_UNLEASH_ELEMENTS=73680
local SPELL_FERAL_SPIRIT=51533
local SPELL_ASCENDANCE=114049
local SPELL_FIRE_ELEMENTAL=2894
local SPELL_MAELSTROM_WEAPON=53817
local SPELL_FLAMETONGUE=8024
local SPELL_WINDFURY=8232
local COOLDOWN_FERAL_SPIRIT=120
local COOLDOWN_ASCENDANCE=180
local SOUND_KEY_MAELSTROM="maelstrom"
local SOUND_KEY_FERAL_SPIRIT="feralSpirit"
local TRACKED_BUFFS={[SPELL_MAELSTROM_WEAPON]=true,[SPELL_ASCENDANCE]=true,[SPELL_FLAMETONGUE]=true,[SPELL_WINDFURY]=true}
local TRACKED_DEBUFFS={[SPELL_FLAME_SHOCK]=true}
local TRACKED_CASTS={[SPELL_STORMSTRIKE]=true,[SPELL_LAVA_LASH]=true,[SPELL_FLAME_SHOCK]=true,[SPELL_EARTH_SHOCK]=true,[SPELL_LIGHTNING_BOLT]=true,[SPELL_UNLEASH_ELEMENTS]=true,[SPELL_FERAL_SPIRIT]=true}
local function EH(c,s)c[s]=c[s]or{}return c[s]end
function module.SupportsSpec(a)if a.player.class~=module.class then return false end if a.player.specId==module.specId then return true end local sk=utils.NormalizeSpecKey(a.player.specName)if sk==module.specKey then return true end if a.player.specIndex==module.specIndex then return true end return false end
function module.OnPlayerInit(a)if a.player.class~=module.class then return end if a.player.specName~="Unknown"then return end if IsSpellKnown and IsSpellKnown(SPELL_STORMSTRIKE)then a.player.specName="Enhancement"a.player.specId=a.player.specId or module.specId a.player.specIndex=a.player.specIndex or module.specIndex end end
function module.GetDefaultSettings()return{sounds={[SOUND_KEY_MAELSTROM]={enabled=true,sound="Sound\\Interface\\RaidWarning.ogg"},[SOUND_KEY_FERAL_SPIRIT]={enabled=true,sound="Sound\\Interface\\MapPing.ogg"}}}end
function module.GetSoundOptions()return{{key=SOUND_KEY_MAELSTROM,label="Maelstrom 5 stacks"},{key=SOUND_KEY_FERAL_SPIRIT,label="Feral Spirit"}}end
function module.IsTrackedBuffSpell(s)return TRACKED_BUFFS[s]==true end
function module.IsTrackedDebuffSpell(s)return TRACKED_DEBUFFS[s]==true end
function module.IsTrackedCast(s)return TRACKED_CASTS[s]==true end
function module.ShouldRecordCast(e)if not e or not e.spellId then return false end return TRACKED_CASTS[e.spellId]==true end
function module.GetProcInfo(s)if s==SPELL_MAELSTROM_WEAPON then return{soundKey=SOUND_KEY_MAELSTROM,priority=2}elseif s==SPELL_FERAL_SPIRIT then return{soundKey=SOUND_KEY_FERAL_SPIRIT,priority=3}end return nil end
function module.InitFight(_,f)f.procs={maelstromStacks=0,maelstromConsumed=0}f.cooldowns={feralSpiritLast=0,ascendanceLast=0}f.castLog={}f.buffHistory={}f.debuffHistory={}f.rotation={totalCasts=0,optimalCasts=0,suboptimalCasts=0,mistakes={},penaltySum=0}end
function module.TrackSpellCast(a,s,t)local f=a.fight if not f or not TRACKED_CASTS[s]then return end local n=utils.NormalizeTimestamp(t)f.spells[s]=(f.spells[s]or 0)+1 table.insert(f.castLog,{spellId=s,timestamp=n})if s==SPELL_LIGHTNING_BOLT then local b=f.buffs[SPELL_MAELSTROM_WEAPON]if b and(b.stacks or 0)>=5 then f.procs.maelstromConsumed=f.procs.maelstromConsumed+1 b.consumed=true b.stacks=0 end elseif s==SPELL_FERAL_SPIRIT then f.cooldowns.feralSpiritLast=n a:AddTimelineEvent(s,n,"cooldown")a:AddEventLog(n,"Feral Spirit",s)end local cS={[SPELL_STORMSTRIKE]=true,[SPELL_LAVA_LASH]=true,[SPELL_FLAME_SHOCK]=true,[SPELL_EARTH_SHOCK]=true,[SPELL_LIGHTNING_BOLT]=true,[SPELL_UNLEASH_ELEMENTS]=true}if cS[s]and f.rotation then local ev=module.EvaluateCast(a,f,s,n)if ev then module.RecordCastEvaluation(f,ev,n)end end end
function module.TrackAura(a,se,s,am,t)local f=a.fight if not f then return end local n=utils.NormalizeTimestamp(t)if se=="SPELL_AURA_APPLIED"or se=="SPELL_AURA_APPLIED_DOSE"or se=="SPELL_AURA_REFRESH"then local st=am or 1 local b=f.buffs[s]local isR=(se=="SPELL_AURA_REFRESH")if b and isR and b.since then f.buffUptime[s]=(f.buffUptime[s]or 0)+(n-b.since)end if not b then b={stacks=st,since=n}f.buffs[s]=b else b.stacks=st b.since=b.since or n end if isR then b.since=n end local h=EH(f.buffHistory,s)if isR and b.historyEntry and not b.historyEntry.removed then b.historyEntry.removed=n end if not b.historyEntry or isR then b.historyEntry={applied=n}table.insert(h,b.historyEntry)end if s==SPELL_MAELSTROM_WEAPON and st>=5 then a:PlayAlertSound(SOUND_KEY_MAELSTROM,n)elseif s==SPELL_ASCENDANCE then f.cooldowns.ascendanceLast=n a:AddTimelineEvent(s,n,"cooldown")a:AddEventLog(n,"Ascendance",s)end elseif se=="SPELL_AURA_REMOVED"then local b=f.buffs[s]if b then if b.since then f.buffUptime[s]=(f.buffUptime[s]or 0)+(n-b.since)end if b.historyEntry and not b.historyEntry.removed then b.historyEntry.removed=n end end f.buffs[s]=nil end end
function module.TrackDebuff(a,se,s,dG,dN,t)local f=a.fight if not f or not TRACKED_DEBUFFS[s]then return end local n=utils.NormalizeTimestamp(t)if not f.primaryTargetGUID then f.primaryTargetGUID=dG end if dG and f.primaryTargetGUID and dG~=f.primaryTargetGUID then return end if dG then f.targets[dG]=true end local d=f.debuffs[s]local h=EH(f.debuffHistory,s)if se=="SPELL_AURA_APPLIED"then f.debuffs[s]={since=n,targetGUID=dG}local e={applied=n}table.insert(h,e)f.debuffs[s].historyEntry=e elseif se=="SPELL_AURA_REFRESH"then if d and d.since then f.debuffUptime[s]=(f.debuffUptime[s]or 0)+(n-d.since)end if d and d.historyEntry and not d.historyEntry.removed then d.historyEntry.removed=n end f.debuffs[s]={since=n,targetGUID=dG}local e={applied=n}table.insert(h,e)f.debuffs[s].historyEntry=e elseif se=="SPELL_AURA_REMOVED"then if d and d.since then f.debuffUptime[s]=(f.debuffUptime[s]or 0)+(n-d.since)end if d and d.historyEntry and not d.historyEntry.removed then d.historyEntry.removed=n end f.debuffs[s]=nil end end
function module.Analyze(a,f,c)local m={}local i={}local sc=100 if c.duration<15 then utils.AddIssue(i,"Walka zbyt krotka.")return{score=0,metrics=m,issues=i}end local function AM(l,s,v,p,st,it,pen)table.insert(m,{label=l,spellId=s,valueText=v or"",percent=p,status=st or"info"})utils.AddIssue(i,it)if pen and pen>0 then sc=utils.Clamp(sc-pen,0,100)end end local fsUp=utils.SafePercent(f.debuffUptime[SPELL_FLAME_SHOCK]or 0,c.duration)local fsSt=utils.StatusForPercent(fsUp,0.95,0.85)AM("Flame Shock uptime",SPELL_FLAME_SHOCK,utils.FormatPercent(fsUp),fsUp,fsSt,fsSt=="bad"and"Niski uptime Flame Shock."or(fsSt=="warn"and"Flame Shock moglby byc wyzszy."or nil),fsSt=="bad"and 12 or(fsSt=="warn"and 6 or 0))local ss=f.spells[SPELL_STORMSTRIKE]or 0 local expSS=utils.ExpectedUses(c.duration,8,5)if expSS>0 then local ssP=utils.SafePercent(ss,expSS)local ssSt=utils.StatusForPercent(ssP,0.85,0.70)AM("Stormstrike uzycia",SPELL_STORMSTRIKE,string.format("%d/%d",ss,expSS),math.min(ssP or 0,1),ssSt,ssSt=="bad"and"Za malo Stormstrike."or(ssSt=="warn"and"Stormstrike uzywany zbyt rzadko."or nil),ssSt=="bad"and 10 or(ssSt=="warn"and 5 or 0))end local fs=f.spells[SPELL_FERAL_SPIRIT]or 0 local expFS=utils.ExpectedUses(c.duration,COOLDOWN_FERAL_SPIRIT,10)if expFS>0 then local fsP=utils.SafePercent(fs,expFS)local fspSt=utils.StatusForPercent(fsP,1.0,0.7)AM("Feral Spirit uzycia",SPELL_FERAL_SPIRIT,string.format("%d/%d",fs,expFS),math.min(fsP or 0,1),fspSt,fs<expFS and"Za malo Feral Spirit."or nil,fs<expFS and 8 or 0)end if f.rotation and f.rotation.totalCasts>0 then local rS=module.GetRotationScore(f)if rS then local rA=rS.accuracy or 0 local rSt=utils.StatusForPercent(rA,0.85,0.70)AM("Dokladnosc rotacji (APL)",nil,string.format("%.0f%% (%d/%d)",rA*100,rS.optimalCasts,rS.totalCasts),rA,rSt,rSt=="bad"and"Niska dokladnosc."or(rSt=="warn"and"Srednia dokladnosc."or nil),rSt=="bad"and 10 or(rSt=="warn"and 5 or 0))if rS.mistakes and #rS.mistakes>0 then local mC={}for _,mk in ipairs(rS.mistakes)do mC[mk.reason or"Unknown"]=(mC[mk.reason or"Unknown"]or 0)+1 end local sM={}for r,ct in pairs(mC)do table.insert(sM,{reason=r,count=ct})end table.sort(sM,function(x,y)return x.count>y.count end)for j=1,math.min(3,#sM)do local mk=sM[j]if mk.count>=2 then utils.AddIssue(i,string.format("Blad rotacji (%dx): %s",mk.count,mk.reason))end end end end end sc=utils.Clamp(sc,0,100)return{score=sc,metrics=m,issues=i}end
function module.GetLiveScore(a,f)if not f then return nil end local n=GetTime()local d=n-f.startTime if d<5 then return nil end return 100 end
local function CPB(s)if not s then return false,0 end for i=1,40 do local _,_,st,_,_,_,_,_,_,aS=UnitBuff("player",i)if not aS then break end if aS==s then return true,st or 1 end end return false,0 end
local function CTD(s)if not s or not UnitExists("target")then return false,0 end for i=1,40 do local _,_,_,_,_,eT,_,c,_,_,aS=UnitDebuff("target",i)if not aS then break end if aS==s and c=="player"then local r=eT and(eT-GetTime())or 0 return true,r end end return false,0 end
function module.GetLiveAdvice(a,f)if not f then return""end local n=GetTime()local d=n-f.startTime local hasMW,mwSt=CPB(SPELL_MAELSTROM_WEAPON)if hasMW and mwSt>=5 then return"Maelstrom 5! Lightning Bolt!"end if UnitExists("target")then local hasFS,fsR=CTD(SPELL_FLAME_SHOCK)if not hasFS and d>2 then return"Naloz Flame Shock!"end if hasFS and fsR>0 and fsR<4 then return"Flame Shock wygasa!"end end if utils.IsSpellReady(SPELL_STORMSTRIKE)then return"Stormstrike!"end if utils.IsSpellReady(SPELL_LAVA_LASH)then return"Lava Lash!"end if utils.IsSpellReady(SPELL_FERAL_SPIRIT)and d>10 then return"Feral Spirit gotowe!"end return""end
function module.GetAdviceSpellIcon(a,f)if not f then return nil end local n=GetTime()local d=n-f.startTime local hasMW,mwSt=CPB(SPELL_MAELSTROM_WEAPON)if hasMW and mwSt>=5 then return SPELL_LIGHTNING_BOLT end if UnitExists("target")then local hasFS,fsR=CTD(SPELL_FLAME_SHOCK)if not hasFS and d>2 then return SPELL_FLAME_SHOCK end if hasFS and fsR>0 and fsR<4 then return SPELL_FLAME_SHOCK end end if utils.IsSpellReady(SPELL_STORMSTRIKE)then return SPELL_STORMSTRIKE end if utils.IsSpellReady(SPELL_LAVA_LASH)then return SPELL_LAVA_LASH end if utils.IsSpellReady(SPELL_FERAL_SPIRIT)and d>10 then return SPELL_FERAL_SPIRIT end return nil end
local APL_PRIORITY={{id="lb_mw5",spellId=SPELL_LIGHTNING_BOLT,name="LB(MW5)",condition=function(s)return s.mwStacks>=5 end,priority=1,category="proc"},{id="ue",spellId=SPELL_UNLEASH_ELEMENTS,name="Unleash Elements",condition=function(s)return s.ueReady end,priority=2,category="damage"},{id="ss",spellId=SPELL_STORMSTRIKE,name="Stormstrike",condition=function(s)return s.ssReady end,priority=3,category="damage"},{id="fs_m",spellId=SPELL_FLAME_SHOCK,name="Flame Shock",condition=function(s)return s.fsMissing and s.duration>2 end,priority=4,category="dot"},{id="ll",spellId=SPELL_LAVA_LASH,name="Lava Lash",condition=function(s)return s.llReady end,priority=5,category="damage"},{id="fs_r",spellId=SPELL_FLAME_SHOCK,name="Flame Shock(r)",condition=function(s)return s.fsExpiring end,priority=6,category="dot"},{id="es",spellId=SPELL_EARTH_SHOCK,name="Earth Shock",condition=function(s)return true end,priority=7,category="filler"}}
local function GCS(a,f)local s={duration=0,mwStacks=0,ssReady=false,llReady=false,ueReady=false,fsMissing=false,fsExpiring=false}if not f then return s end local n=GetTime()s.duration=n-(f.startTime or n)local hasMW,mwSt=CPB(SPELL_MAELSTROM_WEAPON)s.mwStacks=mwSt or 0 s.ssReady=utils.IsSpellReady(SPELL_STORMSTRIKE)s.llReady=utils.IsSpellReady(SPELL_LAVA_LASH)s.ueReady=utils.IsSpellReady(SPELL_UNLEASH_ELEMENTS)if UnitExists("target")and s.duration>2 then local hasFS,fsR=CTD(SPELL_FLAME_SHOCK)s.fsMissing=not hasFS s.fsExpiring=hasFS and fsR>0 and fsR<4 end return s end
function module.GetNextAPLAction(a,f)local s=GCS(a,f)for _,act in ipairs(APL_PRIORITY)do if act.condition(s)then return act end end return APL_PRIORITY[#APL_PRIORITY]end
function module.GetAPLPriorityList()return APL_PRIORITY end
function module.GetRotationState(a,f)return GCS(a,f)end
function module.EvaluateCast(a,f,sid,ts)local nA=module.GetNextAPLAction(a,f)if not nA then return nil end local isO=(nA.spellId==sid)local pen=0 local rsn=""if not isO then local cP=nil for _,act in ipairs(APL_PRIORITY)do if act.spellId==sid then cP=act.priority break end end if cP then pen=math.abs(nA.priority-cP)*2 rsn=string.format("Powinienes: %s",nA.name)else pen=5 rsn="Spell poza APL"end end return{isOptimal=isO,penalty=pen,reason=rsn,expectedSpell=nA.spellId,expectedName=nA.name,actualSpell=sid}end
function module.RecordCastEvaluation(f,ev,ts)if not f.rotation then return end f.rotation.totalCasts=f.rotation.totalCasts+1 if ev.isOptimal then f.rotation.optimalCasts=f.rotation.optimalCasts+1 else f.rotation.suboptimalCasts=f.rotation.suboptimalCasts+1 f.rotation.penaltySum=f.rotation.penaltySum+ev.penalty table.insert(f.rotation.mistakes,{timestamp=ts,reason=ev.reason,penalty=ev.penalty,expected=ev.expectedName})end end
function module.GetRotationScore(f)if not f.rotation or f.rotation.totalCasts==0 then return nil end return{accuracy=f.rotation.optimalCasts/f.rotation.totalCasts,totalCasts=f.rotation.totalCasts,optimalCasts=f.rotation.optimalCasts,suboptimalCasts=f.rotation.suboptimalCasts,mistakes=f.rotation.mistakes,penaltySum=f.rotation.penaltySum}end
Analyzer:RegisterClassModule(module.class,module)
