local _,Analyzer=...if not Analyzer then return end
local module={}
local utils=Analyzer.utils
module.name="Warlock - Destruction"
module.class="WARLOCK"
module.specKey="destruction"
module.specIndex=3
module.specId=267
local SPELL_INCINERATE=29722
local SPELL_IMMOLATE=348
local SPELL_CONFLAGRATE=17962
local SPELL_CHAOS_BOLT=116858
local SPELL_SHADOWBURN=17877
local SPELL_RAIN_OF_FIRE=5740
local SPELL_HAVOC=80240
local SPELL_DARK_SOUL_INSTABILITY=113858
local SPELL_SUMMON_DOOMGUARD=18540
local SPELL_FIRE_AND_BRIMSTONE=108683
local SPELL_BACKDRAFT=117896
local SPELL_BURNING_EMBERS=108647
local COOLDOWN_DARK_SOUL=120
local COOLDOWN_CONFLAGRATE=12
local SOUND_KEY_BACKDRAFT="backdraft"
local SOUND_KEY_DARK_SOUL="darkSoul"
local TRACKED_BUFFS={[SPELL_DARK_SOUL_INSTABILITY]=true,[SPELL_BACKDRAFT]=true,[SPELL_FIRE_AND_BRIMSTONE]=true}
local TRACKED_DEBUFFS={[SPELL_IMMOLATE]=true,[SPELL_HAVOC]=true}
local TRACKED_CASTS={[SPELL_INCINERATE]=true,[SPELL_IMMOLATE]=true,[SPELL_CONFLAGRATE]=true,[SPELL_CHAOS_BOLT]=true,[SPELL_SHADOWBURN]=true,[SPELL_RAIN_OF_FIRE]=true}
local function EH(c,s)c[s]=c[s]or{}return c[s]end
function module.SupportsSpec(a)if a.player.class~=module.class then return false end if a.player.specId==module.specId then return true end local sk=utils.NormalizeSpecKey(a.player.specName)if sk==module.specKey then return true end if a.player.specIndex==module.specIndex then return true end return false end
function module.OnPlayerInit(a)if a.player.class~=module.class then return end if a.player.specName~="Unknown"then return end if IsSpellKnown and IsSpellKnown(SPELL_CHAOS_BOLT)then a.player.specName="Destruction"a.player.specId=a.player.specId or module.specId a.player.specIndex=a.player.specIndex or module.specIndex end end
function module.GetDefaultSettings()return{sounds={[SOUND_KEY_BACKDRAFT]={enabled=true,sound="Sound\\Interface\\RaidWarning.ogg"},[SOUND_KEY_DARK_SOUL]={enabled=true,sound="Sound\\Interface\\MapPing.ogg"}}}end
function module.GetSoundOptions()return{{key=SOUND_KEY_BACKDRAFT,label="Backdraft"},{key=SOUND_KEY_DARK_SOUL,label="Dark Soul"}}end
function module.IsTrackedBuffSpell(s)return TRACKED_BUFFS[s]==true end
function module.IsTrackedDebuffSpell(s)return TRACKED_DEBUFFS[s]==true end
function module.IsTrackedCast(s)return TRACKED_CASTS[s]==true end
function module.ShouldRecordCast(e)if not e or not e.spellId then return false end return TRACKED_CASTS[e.spellId]==true end
function module.GetProcInfo(s)if s==SPELL_BACKDRAFT then return{soundKey=SOUND_KEY_BACKDRAFT,priority=2}elseif s==SPELL_DARK_SOUL_INSTABILITY then return{soundKey=SOUND_KEY_DARK_SOUL,priority=3}end return nil end
function module.InitFight(_,f)f.procs={backdraftStacks=0}f.cooldowns={darkSoulLast=0,conflagrateLast=0}f.castLog={}f.buffHistory={}f.debuffHistory={}f.rotation={totalCasts=0,optimalCasts=0,suboptimalCasts=0,mistakes={},penaltySum=0}end
function module.TrackSpellCast(a,s,t)local f=a.fight if not f or not TRACKED_CASTS[s]then return end local n=utils.NormalizeTimestamp(t)f.spells[s]=(f.spells[s]or 0)+1 table.insert(f.castLog,{spellId=s,timestamp=n})if s==SPELL_CONFLAGRATE then f.cooldowns.conflagrateLast=n a:AddEventLog(n,"Conflagrate",s)elseif s==SPELL_CHAOS_BOLT then a:AddEventLog(n,"Chaos Bolt",s)elseif s==SPELL_DARK_SOUL_INSTABILITY then f.cooldowns.darkSoulLast=n a:AddTimelineEvent(s,n,"cooldown")a:AddEventLog(n,"Dark Soul",s)end local cS={[SPELL_INCINERATE]=true,[SPELL_IMMOLATE]=true,[SPELL_CONFLAGRATE]=true,[SPELL_CHAOS_BOLT]=true}if cS[s]and f.rotation then local ev=module.EvaluateCast(a,f,s,n)if ev then module.RecordCastEvaluation(f,ev,n)end end end
function module.TrackAura(a,se,s,am,t)local f=a.fight if not f then return end local n=utils.NormalizeTimestamp(t)if se=="SPELL_AURA_APPLIED"or se=="SPELL_AURA_APPLIED_DOSE"or se=="SPELL_AURA_REFRESH"then local st=am or 1 local b=f.buffs[s]local isR=(se=="SPELL_AURA_REFRESH")if b and isR and b.since then f.buffUptime[s]=(f.buffUptime[s]or 0)+(n-b.since)end if not b then b={stacks=st,since=n}f.buffs[s]=b else b.stacks=st b.since=b.since or n end if isR then b.since=n end local h=EH(f.buffHistory,s)if isR and b.historyEntry and not b.historyEntry.removed then b.historyEntry.removed=n end if not b.historyEntry or isR then b.historyEntry={applied=n}table.insert(h,b.historyEntry)end if s==SPELL_BACKDRAFT then a:PlayAlertSound(SOUND_KEY_BACKDRAFT,n)elseif s==SPELL_DARK_SOUL_INSTABILITY then a:PlayAlertSound(SOUND_KEY_DARK_SOUL,n)end elseif se=="SPELL_AURA_REMOVED"then local b=f.buffs[s]if b then if b.since then f.buffUptime[s]=(f.buffUptime[s]or 0)+(n-b.since)end if b.historyEntry and not b.historyEntry.removed then b.historyEntry.removed=n end end f.buffs[s]=nil end end
function module.TrackDebuff(a,se,s,dG,dN,t)local f=a.fight if not f or not TRACKED_DEBUFFS[s]then return end local n=utils.NormalizeTimestamp(t)if not f.primaryTargetGUID then f.primaryTargetGUID=dG end if dG and f.primaryTargetGUID and dG~=f.primaryTargetGUID then return end if dG then f.targets[dG]=true end local d=f.debuffs[s]local h=EH(f.debuffHistory,s)if se=="SPELL_AURA_APPLIED"then f.debuffs[s]={since=n,targetGUID=dG}local e={applied=n}table.insert(h,e)f.debuffs[s].historyEntry=e elseif se=="SPELL_AURA_REFRESH"then if d and d.since then f.debuffUptime[s]=(f.debuffUptime[s]or 0)+(n-d.since)end if d and d.historyEntry and not d.historyEntry.removed then d.historyEntry.removed=n end f.debuffs[s]={since=n,targetGUID=dG}local e={applied=n}table.insert(h,e)f.debuffs[s].historyEntry=e elseif se=="SPELL_AURA_REMOVED"then if d and d.since then f.debuffUptime[s]=(f.debuffUptime[s]or 0)+(n-d.since)end if d and d.historyEntry and not d.historyEntry.removed then d.historyEntry.removed=n end f.debuffs[s]=nil end end
function module.Analyze(a,f,c)local m={}local i={}local sc=100 if c.duration<15 then utils.AddIssue(i,"Walka zbyt krotka.")return{score=0,metrics=m,issues=i}end local function AM(l,s,v,p,st,it,pen)table.insert(m,{label=l,spellId=s,valueText=v or"",percent=p,status=st or"info"})utils.AddIssue(i,it)if pen and pen>0 then sc=utils.Clamp(sc-pen,0,100)end end local immUp=utils.SafePercent(f.debuffUptime[SPELL_IMMOLATE]or 0,c.duration)local immSt=utils.StatusForPercent(immUp,0.95,0.85)AM("Immolate uptime",SPELL_IMMOLATE,utils.FormatPercent(immUp),immUp,immSt,immSt=="bad"and"Niski uptime Immolate."or(immSt=="warn"and"Immolate moglby byc wyzszy."or nil),immSt=="bad"and 15 or(immSt=="warn"and 8 or 0))local cb=f.spells[SPELL_CHAOS_BOLT]or 0 local expCB=utils.ExpectedUses(c.duration,8,5)if expCB>0 then local cbP=utils.SafePercent(cb,expCB)local cbSt=utils.StatusForPercent(cbP,0.80,0.60)AM("Chaos Bolt uzycia",SPELL_CHAOS_BOLT,string.format("%d/%d",cb,expCB),math.min(cbP or 0,1),cbSt,cbSt=="bad"and"Za malo Chaos Bolt."or(cbSt=="warn"and"Chaos Bolt uzywany zbyt rzadko."or nil),cbSt=="bad"and 10 or(cbSt=="warn"and 5 or 0))end local ds=f.spells[SPELL_DARK_SOUL_INSTABILITY]or 0 local expDS=utils.ExpectedUses(c.duration,COOLDOWN_DARK_SOUL,10)if expDS>0 then local dsP=utils.SafePercent(ds,expDS)local dsSt=utils.StatusForPercent(dsP,1.0,0.7)AM("Dark Soul uzycia",SPELL_DARK_SOUL_INSTABILITY,string.format("%d/%d",ds,expDS),math.min(dsP or 0,1),dsSt,ds<expDS and"Za malo Dark Soul."or nil,ds<expDS and 8 or 0)end if f.rotation and f.rotation.totalCasts>0 then local rS=module.GetRotationScore(f)if rS then local rA=rS.accuracy or 0 local rSt=utils.StatusForPercent(rA,0.85,0.70)AM("Dokladnosc rotacji (APL)",nil,string.format("%.0f%% (%d/%d)",rA*100,rS.optimalCasts,rS.totalCasts),rA,rSt,rSt=="bad"and"Niska dokladnosc."or(rSt=="warn"and"Srednia dokladnosc."or nil),rSt=="bad"and 10 or(rSt=="warn"and 5 or 0))if rS.mistakes and #rS.mistakes>0 then local mC={}for _,mk in ipairs(rS.mistakes)do mC[mk.reason or"Unknown"]=(mC[mk.reason or"Unknown"]or 0)+1 end local sM={}for r,ct in pairs(mC)do table.insert(sM,{reason=r,count=ct})end table.sort(sM,function(x,y)return x.count>y.count end)for j=1,math.min(3,#sM)do local mk=sM[j]if mk.count>=2 then utils.AddIssue(i,string.format("Blad rotacji (%dx): %s",mk.count,mk.reason))end end end end end sc=utils.Clamp(sc,0,100)return{score=sc,metrics=m,issues=i}end
function module.GetLiveScore(a,f)if not f then return nil end local n=GetTime()local d=n-f.startTime if d<5 then return nil end return 100 end
local function CPB(s)if not s then return false end for i=1,40 do local _,_,_,_,_,_,_,_,_,aS=UnitBuff("player",i)if not aS then break end if aS==s then return true end end return false end
local function CTD(s)if not s or not UnitExists("target")then return false,0 end for i=1,40 do local _,_,_,_,_,eT,_,c,_,_,aS=UnitDebuff("target",i)if not aS then break end if aS==s and c=="player"then local r=eT and(eT-GetTime())or 0 return true,r end end return false,0 end
local function GetEmbers()if UnitPower then return UnitPower("player",14)/10 end return 0 end
function module.GetLiveAdvice(a,f)if not f then return""end local n=GetTime()local d=n-f.startTime local embers=GetEmbers()if embers>=3.5 then return"Duzo Embers! Chaos Bolt!"end if UnitExists("target")then local hasImm,immR=CTD(SPELL_IMMOLATE)if not hasImm and d>2 then return"Naloz Immolate!"end if hasImm and immR>0 and immR<4 then return"Immolate wygasa!"end end if utils.IsSpellReady(SPELL_CONFLAGRATE)then return"Conflagrate!"end if utils.IsSpellReady(SPELL_DARK_SOUL_INSTABILITY)and d>10 then return"Dark Soul gotowe!"end return""end
function module.GetAdviceSpellIcon(a,f)if not f then return nil end local n=GetTime()local d=n-f.startTime local embers=GetEmbers()if embers>=3.5 then return SPELL_CHAOS_BOLT end if UnitExists("target")then local hasImm,immR=CTD(SPELL_IMMOLATE)if not hasImm and d>2 then return SPELL_IMMOLATE end if hasImm and immR>0 and immR<4 then return SPELL_IMMOLATE end end if utils.IsSpellReady(SPELL_CONFLAGRATE)then return SPELL_CONFLAGRATE end if utils.IsSpellReady(SPELL_DARK_SOUL_INSTABILITY)and d>10 then return SPELL_DARK_SOUL_INSTABILITY end return nil end
local APL_PRIORITY={{id="ds",spellId=SPELL_DARK_SOUL_INSTABILITY,name="Dark Soul",condition=function(s)return s.dsReady and s.duration>10 end,priority=1,category="cooldown"},{id="imm_m",spellId=SPELL_IMMOLATE,name="Immolate",condition=function(s)return s.immMissing and s.duration>2 end,priority=2,category="dot"},{id="cb_cap",spellId=SPELL_CHAOS_BOLT,name="Chaos Bolt(cap)",condition=function(s)return s.embers>=3.5 end,priority=3,category="spender"},{id="conf",spellId=SPELL_CONFLAGRATE,name="Conflagrate",condition=function(s)return s.confReady end,priority=4,category="damage"},{id="imm_r",spellId=SPELL_IMMOLATE,name="Immolate(r)",condition=function(s)return s.immExpiring end,priority=5,category="dot"},{id="cb",spellId=SPELL_CHAOS_BOLT,name="Chaos Bolt",condition=function(s)return s.embers>=1 and s.backdraft end,priority=6,category="spender"},{id="inc",spellId=SPELL_INCINERATE,name="Incinerate",condition=function(s)return true end,priority=7,category="filler"}}
local function GCS(a,f)local s={duration=0,embers=0,immMissing=false,immExpiring=false,backdraft=false,confReady=false,dsReady=false}if not f then return s end local n=GetTime()s.duration=n-(f.startTime or n)s.embers=GetEmbers()s.backdraft=CPB(SPELL_BACKDRAFT)s.confReady=utils.IsSpellReady(SPELL_CONFLAGRATE)s.dsReady=utils.IsSpellReady(SPELL_DARK_SOUL_INSTABILITY)if UnitExists("target")and s.duration>2 then local hasImm,immR=CTD(SPELL_IMMOLATE)s.immMissing=not hasImm s.immExpiring=hasImm and immR>0 and immR<4 end return s end
function module.GetNextAPLAction(a,f)local s=GCS(a,f)for _,act in ipairs(APL_PRIORITY)do if act.condition(s)then return act end end return APL_PRIORITY[#APL_PRIORITY]end
function module.GetAPLPriorityList()return APL_PRIORITY end
function module.GetRotationState(a,f)return GCS(a,f)end
function module.EvaluateCast(a,f,sid,ts)local nA=module.GetNextAPLAction(a,f)if not nA then return nil end local isO=(nA.spellId==sid)local pen=0 local rsn=""if not isO then local cP=nil for _,act in ipairs(APL_PRIORITY)do if act.spellId==sid then cP=act.priority break end end if cP then pen=math.abs(nA.priority-cP)*2 rsn=string.format("Powinienes: %s",nA.name)else pen=5 rsn="Spell poza APL"end end return{isOptimal=isO,penalty=pen,reason=rsn,expectedSpell=nA.spellId,expectedName=nA.name,actualSpell=sid}end
function module.RecordCastEvaluation(f,ev,ts)if not f.rotation then return end f.rotation.totalCasts=f.rotation.totalCasts+1 if ev.isOptimal then f.rotation.optimalCasts=f.rotation.optimalCasts+1 else f.rotation.suboptimalCasts=f.rotation.suboptimalCasts+1 f.rotation.penaltySum=f.rotation.penaltySum+ev.penalty table.insert(f.rotation.mistakes,{timestamp=ts,reason=ev.reason,penalty=ev.penalty,expected=ev.expectedName})end end
function module.GetRotationScore(f)if not f.rotation or f.rotation.totalCasts==0 then return nil end return{accuracy=f.rotation.optimalCasts/f.rotation.totalCasts,totalCasts=f.rotation.totalCasts,optimalCasts=f.rotation.optimalCasts,suboptimalCasts=f.rotation.suboptimalCasts,mistakes=f.rotation.mistakes,penaltySum=f.rotation.penaltySum}end
Analyzer:RegisterClassModule(module.class,module)
