local _,Analyzer=...if not Analyzer then return end
local module={}
local utils=Analyzer.utils
module.name="Warrior - Fury"
module.class="WARRIOR"
module.specKey="fury"
module.specIndex=2
module.specId=72
local SPELL_BLOODTHIRST=23881
local SPELL_RAGING_BLOW=85288
local SPELL_COLOSSUS_SMASH=86346
local SPELL_WILD_STRIKE=100130
local SPELL_HEROIC_STRIKE=78
local SPELL_EXECUTE=5308
local SPELL_BERSERKER_RAGE=18499
local SPELL_RECKLESSNESS=1719
local SPELL_SKULL_BANNER=114207
local SPELL_BLOODBATH=12292
local SPELL_AVATAR=107574
local SPELL_STORM_BOLT=107570
local SPELL_DRAGON_ROAR=118000
local SPELL_ENRAGE=12880
local SPELL_RAGING_BLOW_BUFF=131116
local SPELL_MEAT_CLEAVER=85739
local COOLDOWN_RECKLESSNESS=180
local COOLDOWN_SKULL_BANNER=180
local SOUND_KEY_ENRAGE="enrage"
local SOUND_KEY_RAGING_BLOW="ragingBlow"
local TRACKED_BUFFS={[SPELL_ENRAGE]=true,[SPELL_RAGING_BLOW_BUFF]=true,[SPELL_RECKLESSNESS]=true,[SPELL_AVATAR]=true,[SPELL_BLOODBATH]=true,[SPELL_MEAT_CLEAVER]=true}
local TRACKED_DEBUFFS={[SPELL_COLOSSUS_SMASH]=true}
local TRACKED_CASTS={[SPELL_BLOODTHIRST]=true,[SPELL_RAGING_BLOW]=true,[SPELL_COLOSSUS_SMASH]=true,[SPELL_WILD_STRIKE]=true,[SPELL_HEROIC_STRIKE]=true,[SPELL_EXECUTE]=true,[SPELL_BERSERKER_RAGE]=true}
local function EH(c,s)c[s]=c[s]or{}return c[s]end
function module.SupportsSpec(a)if a.player.class~=module.class then return false end if a.player.specId==module.specId then return true end local sk=utils.NormalizeSpecKey(a.player.specName)if sk==module.specKey then return true end if a.player.specIndex==module.specIndex then return true end return false end
function module.OnPlayerInit(a)if a.player.class~=module.class then return end if a.player.specName~="Unknown"then return end if IsSpellKnown and IsSpellKnown(SPELL_BLOODTHIRST)then a.player.specName="Fury"a.player.specId=a.player.specId or module.specId a.player.specIndex=a.player.specIndex or module.specIndex end end
function module.GetDefaultSettings()return{sounds={[SOUND_KEY_ENRAGE]={enabled=true,sound="Sound\\Interface\\RaidWarning.ogg"},[SOUND_KEY_RAGING_BLOW]={enabled=true,sound="Sound\\Interface\\MapPing.ogg"}}}end
function module.GetSoundOptions()return{{key=SOUND_KEY_ENRAGE,label="Enrage"},{key=SOUND_KEY_RAGING_BLOW,label="Raging Blow Ready"}}end
function module.IsTrackedBuffSpell(s)return TRACKED_BUFFS[s]==true end
function module.IsTrackedDebuffSpell(s)return TRACKED_DEBUFFS[s]==true end
function module.IsTrackedCast(s)return TRACKED_CASTS[s]==true end
function module.ShouldRecordCast(e)if not e or not e.spellId then return false end return TRACKED_CASTS[e.spellId]==true end
function module.GetProcInfo(s)if s==SPELL_ENRAGE then return{soundKey=SOUND_KEY_ENRAGE,priority=2}elseif s==SPELL_RAGING_BLOW_BUFF then return{soundKey=SOUND_KEY_RAGING_BLOW,priority=3}end return nil end
function module.InitFight(_,f)f.procs={enrageProcs=0,ragingBlowStacks=0}f.cooldowns={recklessnessLast=0,skullBannerLast=0}f.castLog={}f.buffHistory={}f.debuffHistory={}f.rotation={totalCasts=0,optimalCasts=0,suboptimalCasts=0,mistakes={},penaltySum=0}end
function module.TrackSpellCast(a,s,t)local f=a.fight if not f or not TRACKED_CASTS[s]then return end local n=utils.NormalizeTimestamp(t)f.spells[s]=(f.spells[s]or 0)+1 table.insert(f.castLog,{spellId=s,timestamp=n})if s==SPELL_RECKLESSNESS then f.cooldowns.recklessnessLast=n a:AddTimelineEvent(s,n,"cooldown")a:AddEventLog(n,"Recklessness",s)elseif s==SPELL_COLOSSUS_SMASH then a:AddEventLog(n,"Colossus Smash",s)end local cS={[SPELL_BLOODTHIRST]=true,[SPELL_RAGING_BLOW]=true,[SPELL_COLOSSUS_SMASH]=true,[SPELL_WILD_STRIKE]=true,[SPELL_EXECUTE]=true}if cS[s]and f.rotation then local ev=module.EvaluateCast(a,f,s,n)if ev then module.RecordCastEvaluation(f,ev,n)end end end
function module.TrackAura(a,se,s,am,t)local f=a.fight if not f then return end local n=utils.NormalizeTimestamp(t)if se=="SPELL_AURA_APPLIED"or se=="SPELL_AURA_APPLIED_DOSE"or se=="SPELL_AURA_REFRESH"then local st=am or 1 local b=f.buffs[s]local isR=(se=="SPELL_AURA_REFRESH")if b and isR and b.since then f.buffUptime[s]=(f.buffUptime[s]or 0)+(n-b.since)end if not b then b={stacks=st,since=n}f.buffs[s]=b else b.stacks=st b.since=b.since or n end if isR then b.since=n end local h=EH(f.buffHistory,s)if isR and b.historyEntry and not b.historyEntry.removed then b.historyEntry.removed=n end if not b.historyEntry or isR then b.historyEntry={applied=n}table.insert(h,b.historyEntry)end if s==SPELL_ENRAGE then if not isR then f.procs.enrageProcs=f.procs.enrageProcs+1 a:AddTimelineEvent(s,n,"proc")end a:PlayAlertSound(SOUND_KEY_ENRAGE,n)elseif s==SPELL_RAGING_BLOW_BUFF then a:PlayAlertSound(SOUND_KEY_RAGING_BLOW,n)end elseif se=="SPELL_AURA_REMOVED"then local b=f.buffs[s]if b then if b.since then f.buffUptime[s]=(f.buffUptime[s]or 0)+(n-b.since)end if b.historyEntry and not b.historyEntry.removed then b.historyEntry.removed=n end end f.buffs[s]=nil end end
function module.TrackDebuff(a,se,s,dG,dN,t)local f=a.fight if not f or not TRACKED_DEBUFFS[s]then return end local n=utils.NormalizeTimestamp(t)if not f.primaryTargetGUID then f.primaryTargetGUID=dG end if dG and f.primaryTargetGUID and dG~=f.primaryTargetGUID then return end if dG then f.targets[dG]=true end local d=f.debuffs[s]local h=EH(f.debuffHistory,s)if se=="SPELL_AURA_APPLIED"then f.debuffs[s]={since=n,targetGUID=dG}local e={applied=n}table.insert(h,e)f.debuffs[s].historyEntry=e elseif se=="SPELL_AURA_REFRESH"then if d and d.since then f.debuffUptime[s]=(f.debuffUptime[s]or 0)+(n-d.since)end if d and d.historyEntry and not d.historyEntry.removed then d.historyEntry.removed=n end f.debuffs[s]={since=n,targetGUID=dG}local e={applied=n}table.insert(h,e)f.debuffs[s].historyEntry=e elseif se=="SPELL_AURA_REMOVED"then if d and d.since then f.debuffUptime[s]=(f.debuffUptime[s]or 0)+(n-d.since)end if d and d.historyEntry and not d.historyEntry.removed then d.historyEntry.removed=n end f.debuffs[s]=nil end end
function module.Analyze(a,f,c)local m={}local i={}local sc=100 if c.duration<15 then utils.AddIssue(i,"Walka zbyt krotka.")return{score=0,metrics=m,issues=i}end local function AM(l,s,v,p,st,it,pen)table.insert(m,{label=l,spellId=s,valueText=v or"",percent=p,status=st or"info"})utils.AddIssue(i,it)if pen and pen>0 then sc=utils.Clamp(sc-pen,0,100)end end local enrUp=utils.SafePercent(f.buffUptime[SPELL_ENRAGE]or 0,c.duration)local enrSt=utils.StatusForPercent(enrUp,0.85,0.70)AM("Enrage uptime",SPELL_ENRAGE,utils.FormatPercent(enrUp),enrUp,enrSt,enrSt=="bad"and"Niski uptime Enrage."or(enrSt=="warn"and"Enrage moglby byc wyzszy."or nil),enrSt=="bad"and 15 or(enrSt=="warn"and 8 or 0))local bt=f.spells[SPELL_BLOODTHIRST]or 0 local expBT=utils.ExpectedUses(c.duration,4.5,3)if expBT>0 then local btP=utils.SafePercent(bt,expBT)local btSt=utils.StatusForPercent(btP,0.85,0.70)AM("Bloodthirst uzycia",SPELL_BLOODTHIRST,string.format("%d/%d",bt,expBT),math.min(btP or 0,1),btSt,btSt=="bad"and"Za malo Bloodthirst."or(btSt=="warn"and"Bloodthirst uzywany zbyt rzadko."or nil),btSt=="bad"and 10 or(btSt=="warn"and 5 or 0))end local reck=f.spells[SPELL_RECKLESSNESS]or 0 local expR=utils.ExpectedUses(c.duration,COOLDOWN_RECKLESSNESS,10)if expR>0 then local rP=utils.SafePercent(reck,expR)local rSt=utils.StatusForPercent(rP,1.0,0.7)AM("Recklessness uzycia",SPELL_RECKLESSNESS,string.format("%d/%d",reck,expR),math.min(rP or 0,1),rSt,reck<expR and"Za malo Recklessness."or nil,reck<expR and 8 or 0)end if f.rotation and f.rotation.totalCasts>0 then local rS=module.GetRotationScore(f)if rS then local rA=rS.accuracy or 0 local rSt=utils.StatusForPercent(rA,0.85,0.70)AM("Dokladnosc rotacji (APL)",nil,string.format("%.0f%% (%d/%d)",rA*100,rS.optimalCasts,rS.totalCasts),rA,rSt,rSt=="bad"and"Niska dokladnosc."or(rSt=="warn"and"Srednia dokladnosc."or nil),rSt=="bad"and 10 or(rSt=="warn"and 5 or 0))if rS.mistakes and #rS.mistakes>0 then local mC={}for _,mk in ipairs(rS.mistakes)do mC[mk.reason or"Unknown"]=(mC[mk.reason or"Unknown"]or 0)+1 end local sM={}for r,ct in pairs(mC)do table.insert(sM,{reason=r,count=ct})end table.sort(sM,function(x,y)return x.count>y.count end)for j=1,math.min(3,#sM)do local mk=sM[j]if mk.count>=2 then utils.AddIssue(i,string.format("Blad rotacji (%dx): %s",mk.count,mk.reason))end end end end end sc=utils.Clamp(sc,0,100)return{score=sc,metrics=m,issues=i}end
function module.GetLiveScore(a,f)if not f then return nil end local n=GetTime()local d=n-f.startTime if d<5 then return nil end return 100 end
local function CPB(s)if not s then return false end for i=1,40 do local _,_,_,_,_,_,_,_,_,aS=UnitBuff("player",i)if not aS then break end if aS==s then return true end end return false end
local function CTD(s)if not s or not UnitExists("target")then return false end for i=1,40 do local _,_,_,_,_,_,_,c,_,_,aS=UnitDebuff("target",i)if not aS then break end if aS==s and c=="player"then return true end end return false end
local function GetRage()if UnitPower then return UnitPower("player",1)end return 0 end
function module.GetLiveAdvice(a,f)if not f then return""end local n=GetTime()local d=n-f.startTime local hasRB=CPB(SPELL_RAGING_BLOW_BUFF)if hasRB and CPB(SPELL_ENRAGE)then return"Raging Blow! (Enraged)"end if utils.IsSpellReady(SPELL_COLOSSUS_SMASH)then return"Colossus Smash!"end if utils.IsSpellReady(SPELL_BLOODTHIRST)then return"Bloodthirst!"end if hasRB then return"Raging Blow!"end if utils.IsSpellReady(SPELL_RECKLESSNESS)and d>10 then return"Recklessness gotowe!"end return""end
function module.GetAdviceSpellIcon(a,f)if not f then return nil end local n=GetTime()local d=n-f.startTime local hasRB=CPB(SPELL_RAGING_BLOW_BUFF)if hasRB and CPB(SPELL_ENRAGE)then return SPELL_RAGING_BLOW end if utils.IsSpellReady(SPELL_COLOSSUS_SMASH)then return SPELL_COLOSSUS_SMASH end if utils.IsSpellReady(SPELL_BLOODTHIRST)then return SPELL_BLOODTHIRST end if hasRB then return SPELL_RAGING_BLOW end if utils.IsSpellReady(SPELL_RECKLESSNESS)and d>10 then return SPELL_RECKLESSNESS end return nil end
local APL_PRIORITY={{id="cs",spellId=SPELL_COLOSSUS_SMASH,name="Colossus Smash",condition=function(s)return s.csReady end,priority=1,category="debuff"},{id="bt",spellId=SPELL_BLOODTHIRST,name="Bloodthirst",condition=function(s)return s.btReady end,priority=2,category="damage"},{id="rb_enr",spellId=SPELL_RAGING_BLOW,name="Raging Blow(Enr)",condition=function(s)return s.rbReady and s.enraged end,priority=3,category="damage"},{id="exec",spellId=SPELL_EXECUTE,name="Execute",condition=function(s)return s.execReady end,priority=4,category="damage"},{id="rb",spellId=SPELL_RAGING_BLOW,name="Raging Blow",condition=function(s)return s.rbReady end,priority=5,category="damage"},{id="ws",spellId=SPELL_WILD_STRIKE,name="Wild Strike",condition=function(s)return s.rage>=30 end,priority=6,category="filler"}}
local function GCS(a,f)local s={duration=0,rage=0,enraged=false,csReady=false,btReady=false,rbReady=false,execReady=false}if not f then return s end local n=GetTime()s.duration=n-(f.startTime or n)s.rage=GetRage()s.enraged=CPB(SPELL_ENRAGE)s.csReady=utils.IsSpellReady(SPELL_COLOSSUS_SMASH)s.btReady=utils.IsSpellReady(SPELL_BLOODTHIRST)s.rbReady=CPB(SPELL_RAGING_BLOW_BUFF)and utils.IsSpellReady(SPELL_RAGING_BLOW)s.execReady=utils.IsSpellReady(SPELL_EXECUTE)return s end
function module.GetNextAPLAction(a,f)local s=GCS(a,f)for _,act in ipairs(APL_PRIORITY)do if act.condition(s)then return act end end return APL_PRIORITY[#APL_PRIORITY]end
function module.GetAPLPriorityList()return APL_PRIORITY end
function module.GetRotationState(a,f)return GCS(a,f)end
function module.EvaluateCast(a,f,sid,ts)local nA=module.GetNextAPLAction(a,f)if not nA then return nil end local isO=(nA.spellId==sid)local pen=0 local rsn=""if not isO then local cP=nil for _,act in ipairs(APL_PRIORITY)do if act.spellId==sid then cP=act.priority break end end if cP then pen=math.abs(nA.priority-cP)*2 rsn=string.format("Powinienes: %s",nA.name)else pen=5 rsn="Spell poza APL"end end return{isOptimal=isO,penalty=pen,reason=rsn,expectedSpell=nA.spellId,expectedName=nA.name,actualSpell=sid}end
function module.RecordCastEvaluation(f,ev,ts)if not f.rotation then return end f.rotation.totalCasts=f.rotation.totalCasts+1 if ev.isOptimal then f.rotation.optimalCasts=f.rotation.optimalCasts+1 else f.rotation.suboptimalCasts=f.rotation.suboptimalCasts+1 f.rotation.penaltySum=f.rotation.penaltySum+ev.penalty table.insert(f.rotation.mistakes,{timestamp=ts,reason=ev.reason,penalty=ev.penalty,expected=ev.expectedName})end end
function module.GetRotationScore(f)if not f.rotation or f.rotation.totalCasts==0 then return nil end return{accuracy=f.rotation.optimalCasts/f.rotation.totalCasts,totalCasts=f.rotation.totalCasts,optimalCasts=f.rotation.optimalCasts,suboptimalCasts=f.rotation.suboptimalCasts,mistakes=f.rotation.mistakes,penaltySum=f.rotation.penaltySum}end
Analyzer:RegisterClassModule(module.class,module)
